### ISSUE TITLE
Reading/Writing SQLite Databases on SDCard etc

### ISSUE THREAD

**Issue by Meatballs1** [mwrlabs/drozer#124]
If an app decides to store the Database using getExternalFilesDir() or getExternalStorageDirectory() etc then another application with WRITE_EXTERNAL_STORAGE would be able to read/modify it. 

It would be handy if drozer could proxy/perform sqlite commands to simulate another application performing this. Currently you have to download the file/modify it/reupload it etc.

**Comment by HenryHoggard** [comment]
This module supports installation of sqlite3. 
https://github.com/mwrlabs/drozer-modules/blob/master/mwrlabs/tools/setup/sqlite3.py
