### ISSUE TITLE
Environment variables are not correctly substituted in commands

### ISSUE THREAD

**Issue by metall0id** [mwrlabs/drozer#129]
Looking at the following package:
```
dz> run app.package.info -a com.test.bla
Package: com.test.bla
  Application Label: Test
  Process Name: com.test.bla
  Version: 2.957.3
  Data Directory: /data/data/com.test.bla
  APK Path: /data/app/com.test.bla-1.apk
  UID: 10045
  GID: [3003, 1006, 1015]
  Shared Libraries: null
  Shared User ID: null
  ...
```

Now doing the same using the `set` command to replace the package name:
```
dz> set P=com.test.bla
dz> run app.package.info -a $P
could not find the package: $P
```

The env command does confirm that it was set:
```
dz> env
PATH=/data/data/com.mwr.dz/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
WD=/data/data/com.mwr.dz
P=com.test.bla
```
But it doesn't seem to be replaced in the commands I have tested.

**Comment by metall0id** [comment]
PR #146 seems to address this issue, thanks @joaonlima!

Requires final testing before merging.

**Comment by joaonlima** [comment]
Are there any automated tests that I can perform on my end? I've tried to run some with "make tests" but these seem to be failing even without the changes, is there a "correct way" to run them?
