### ISSUE TITLE
Drozer error while connecting [error no 22] invalid argument

### ISSUE THREAD

**Issue by kaleemshaik786** [mwrlabs/drozer#135]
Hi

I have updated the ADT Bundle and I have started the emulator and done the port forwarding. While I connecting to the drozer agent I am getting error saying "Error no 22 invalid argument" May  I know how to resolve this issue.

**Comment by heeeeen** [comment]
Recently i met the same problem when upgrading drozer to 2.3.4. when i use 'drozer console connect’, the agent responded with '[Errno 22] Invalid argument' after drozer logo. so i cannot use drozer console.

i have already reinstalled the agent and my os is mac os x yosemite 10.10.2.
May i know some suggestions? thx a lot!

**Comment by heeeeen** [comment]
i resolved the issue a moment  ago. the method may be helpful.
1. find any older version drozer files and delete them completely including drozer-2.3.3-py2.7.egg directory , .drozer_config things, entries in python .pth files.
2. build the latest commit of branch develop(f97285c 2015-02-19) and install.
