### ISSUE TITLE
Android binaries used by drozer do not work on Android 5.0

### ISSUE THREAD

**Issue by metall0id** [mwrlabs/drozer#139]
As the title suggests, all bundled binaries that are uploaded and run on the device do not work on Android 5.0. This includes:
* weasel
* busybox
* nmap
* possibly some others

When running them on a Lollipop device, the following error message is shown:
`error: only position independent executables (PIE) are supported.`

This is because in Android 5.0 and onward they are enforcing the use of PIE (Position Independent Executables) which helps achieve full ASLR.

The fix for this is using the following line in the `Android.mk` file of these projects:
`APP_PLATFORM := android-16`

However, this means that they will not run on versions of Android prior to 4.1. The approach will have to be to compile 2 versions of each binary and then upload the appropriate one for the version of Android in use.

**Comment by HenryHoggard** [comment]
Busybox now supports PIE.

**Comment by HenryHoggard** [comment]
Closed, splitting into separate issues for each binary.
