### ISSUE TITLE
Install custom module everytime again

### ISSUE THREAD

**Issue by AndreasL123** [mwrlabs/drozer#142]
Hi,
I have a problem with the custom modules I can make a local repository, install the modules and run them but everytime I start ubuntu 14.04 LTS the modules are not installed anymore and I have to reinstall them to use them again.
What do I have to do differently?

**Comment by JosephRedfern** [comment]
Hi,

Hmm, that's odd. Can you launch drozer, create the repository, and then confirm that a line specifying the repository location is being added to your .drozer_config file (normally located at ~/.drozer_config)?

drozer keeps track of local repositories (amongst other things) using this config file, and if it's not being written to when you create your repository then it wont persist between sessions.

**Comment by AndreasL123** [comment]
Thank you.
I couldnt find it but it keeps track of the local repository between sessions.

**Comment by JosephRedfern** [comment]
Hi Andreas - just to confirm, is this problem now fixed?
