### ISSUE TITLE
drozer console connect

### ISSUE THREAD

**Issue by voltaire33010** [mwrlabs/drozer#148]
I got this error in mac os x I just clone the repository
drozer console connect
Traceback (most recent call last):
  File "/drozer/drozer/bin/drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
ImportError: No module named drozer.cli.console

**Comment by JosephRedfern** [comment]
Hi,

You're probably receiving that error because drozer isn't on your Python modules path.

Did you follow the instructions at: https://github.com/mwrlabs/drozer/wiki/Running-on-the-edge? Specifically, "add to your PYTHONPATH /path/to/drozer/src".

You can do this by running `echo \$PYTHONPATH=$PYTHONPATH:/path/to/drozer/src >> ~/.bash_profile"`, where /path/to/drozer/src is the path to the src directory in your local copy of the drozer git repo.

**Comment by voltaire33010** [comment]
thanks, That works!!. Now I have to install jdk 6 on mac so the drozer can works well. is ther any documentation on how to point drozer to the jdk 6 path?
thanks

**Comment by dbradberry** [comment]
You can override the resolution of `javac` on your PATH by adding a reference in ~/.drozer_config:

```
[executables]
javac = /path/to/jdk6/javac
```

That should then be used over any other JDK on your system.

**Comment by voltaire33010** [comment]
That works fine too.  However I finally downloaded a copy of santoku and
everything works beautiful there. All the tools are working fine without
any alteration. Thanks a lot for your help

**Comment by mydockergit** [comment]
Hi,

I have the same issue on Windows 10 x64:  
```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\drozer\Scripts\drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
ImportError: No module named drozer.cli.console
```

This is my **USER** environment variables:
```
C:\Program Files\Java\jre1.8.0_121
C:\Python27
```
This is my **SYSTEM** environment variables:
```
C:\Program Files\Java\jre1.8.0_121
C:\Python27
```

I noticed that here https://github.com/mwrlabs/drozer/wiki/Running-on-the-edge you mentioned that I need to update `PATH`, `PYTHONPATH `and `SDK`  which you didn't specify on the main page of [GitHub](
https://github.com/mwrlabs/drozer), you should update the main page it will safe you questions by other people.  

In the `PYTHONPATH` I didn't understand what you mean by: `/path/to/drozer/src` and `/path/to/drozer/test`.  
These folder are not exist with the windows installation.
After I installed Drozer on Windows, using the MSI, I go two folders:
```
List
Scripts
```  

Bot of them don't contain `src` and `test` folders.
