### ISSUE TITLE
Question : Where should i report issue with sieve A 'Password Manager' App, showcasing some common Android vulnerabilities.

### ISSUE THREAD

**Issue by bugwrangler** [mwrlabs/drozer#154]
It has been crashing over the emulator since last 2 months

**Comment by metall0id** [comment]
Hi,

The Sieve application is not officially supported. It was designed to run on ARM emulators running Android 4.0 and higher for learning purposes.

The last version it was tested on was Android 4.4. Please provide more details on your setup and perhaps we can help.

If the app used to work and is now crashing, perhaps try clearing the application data and opening it again.

Tyrone

**Comment by bugwrangler** [comment]
Am sorry, i was learning hacks over the Genymotion using x86 emulator which could be probable issue. 
Sieve i have tried on 4.2 - it was working fine and all sudden it started crashing while entering or create password entry at latest version of genymotion.

I have given all try but app doesn't support at storing password etc. now at genymotion - could be the architecture issue. thank you!

**Comment by JosephRedfern** [comment]
As I recall, Sieve contains ARM-only native libraries for encryption/decryption, which is probably why it was crashing during password entry under x86. I'd give it a try under an ARM image, if I were you.

**Comment by bugwrangler** [comment]
Sure, will give a try and update you latest observation!

**Comment by raulsiles** [comment]
I can confirm the issue is due to the Sieve's ARM native libraries in an x86 AVD. As soon as you switch to an ARM-based AVD in the Android emulator, everything works as expected. Thanks for the details!

This issue can be closed.
