### ISSUE TITLE
problem with runing weasel in samsung galaxy note 3

### ISSUE THREAD

**Issue by c0otlass** [mwrlabs/drozer#156]
Hi  ...
i have rooted galaxy note 3 ...
i run weasel in my device with root permission ... my server connect to device for a few second but connection terminated so we have not a session to get shell  ... 
i uninstall knox but the problem did not solved!!!
i have no antivirus or firewall ...
my server is stable in my network has no problem
what is the solution?
thanks
best regards

**Comment by metall0id** [comment]
Hi,

Can you please provide the version of Android that your device is running?

Could you perhaps also post the output of `adb logcat` and the drozer server output when you run weasel. With this information we might be able to see what has gone wrong in this process.

Thanks
Tyrone
