### ISSUE TITLE
Could not find Java even if it is on the PATH

### ISSUE THREAD

**Issue by tautology0** [mwrlabs/drozer#159]
Running it one Windows with the JDK, you get the error message:
>C:\tools\drozer>drozer.bat console
>Could not find java. Please ensure that it is installed and on your PATH.

>If this error persists, specify the path in the ~/.drozer_config file:

>   [executables]
>   java = C:\path\to\java

A couple of problems with this:
1. Java *is* on the path, so I shouldn't need to mess around with a config file
2. Can we change the message if it's Windows as ~ could mean c:\users\username or somewhere in the %appdata% directory (where settings should be stored).

**Comment by varadhraj** [comment]
I solved it by changing the configuration.py file in <your path to drozer>/Lib/drozer

I have hardcoded the javac path in the function as given below:
@classmethod
    def executable(cls, name):
        """
        Fetch an executable, could be bundled in the lib, specified in the configuration, or attempt to find it on the PATH
        """
        
  
	print name
        #check the library
	if name == 'javac':		
		path = 'D:\\programs\\java1.6\\bin\\javac.exe'
	else:	
		path = cls.library(name)

        #is the required exe available on the PATH?
        if path == None and cls.get("executables", name) == None:			
            path = system.which(name)
	    
        
        if path == None:		
            path = cls.get("executables", name)
	    
        
        if path == None or path == "":
            sys.stderr.write("Could not find %s. Please ensure that it is installed and on your PATH.\n\nIf this error persists, specify the path in the ~/.drozer_config file:\n\n    [executables]\n    %s = %s\n" % (name, name, platform.system() == "Windows" and "C:\\path\\to\\" + name or "/path/to/" + name))
        
	
        return path
    
This solution works fine for me.

**Comment by pYoo** [comment]
How can I hardcode configuration.py?
It doesn`t open in notepad

**Comment by pYoo** [comment]
It dosen`t WORK

Traceback (most recent call last):
  File "C:\Program Files\drozer\bin\drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
  File "C:\Program Files\drozer\lib\drozer\cli\console.py", line 8, in <module>
    from drozer.console import Console
  File "C:\Program Files\drozer\lib\drozer\console\__init__.py", line 4, in <module>
    from drozer.console.console import Console
  File "C:\Program Files\drozer\lib\drozer\console\console.py", line 6, in <module>
    from pydiesel.api.transport.exceptions import ConnectionError
  File "C:\Program Files\drozer\lib\pydiesel\api\transport\__init__.py", line 5, in <module>
    from socket_transport import SocketTransport
  File "C:\Program Files\drozer\lib\pydiesel\api\transport\socket_transport.py", line 8, in <module>
    from drozer.ssl.provider import Provider # TODO: eugh
  File "C:\Program Files\drozer\lib\drozer\ssl\__init__.py", line 1, in <module>
    from drozer.ssl.ssl_manager import SSLManager
  File "C:\Program Files\drozer\lib\drozer\ssl\ssl_manager.py", line 6, in <module>
    from drozer.ssl.provider import Provider
  File "C:\Program Files\drozer\lib\drozer\ssl\provider.py", line 7, in <module>
    from drozer.configuration import Configuration
  File "C:\Program Files\drozer\lib\drozer\configuration.py", line 26
    if name == 'java':
    ^
IndentationError: unexpected indent

**Comment by pYoo** [comment]
How can I solve another methood below?
I don`t know what that`s mean.

1. If it doesn't already exist, create a file in your home folder (~/ or C:\Users<your name>) called .drozer_config.
2. Insert the following at the bottom of the file:

[executables]
java = C:\path\to\java.exe

**Comment by tautology0** [comment]
This isn't really a support issue: it's a logic issue with drozer: i.e. on Windows it ignores the path and has a badly constructed message.
Has this been fixed or is it just been closed because?

-------- Original message --------

**Comment by truedelguyin** [comment]
does anyone got the solution for using drozer on windows 10, its giving me the same error message, path not found

**Comment by tamtam22** [comment]
@truedelguyin 

Ensure you have Java JDK installed and added `C:\Program Files\Java\jdk<version_no>\bin` to the machine's PATH environment variable

Then type `%userprofile%` in Windows Explorer (should bring you to `C:/users/<your name>`), edit the .drozer_config file there and add in the code below:

```
[executables]
java = C:\Program Files\Java\jdk1.8.0_144\bin
javac = C:\Program Files\Java\jdk1.8.0_144\bin\javac.exe
```

Unfortunately on the latest version 2.6.4 the PATH detection issue still persists.

**Comment by hackerpain** [comment]
> @truedelguyin
> 
> Ensure you have Java JDK installed and added `C:\Program Files\Java\jdk1.8.0_144\bin` to the machine's PATH environment variable
> 
> Then type `%userprofile%` in Windows Explorer (should bring you to `C:/users/<your name>`), edit the .drozer_config file there and add in the code below:
> 
> ```
> [executables]
> java = C:\Program Files\Java\jdk1.8.0_144\bin
> javac = C:\Program Files\Java\jdk1.8.0_144\bin\javac.exe
> ```
> 
> _Edit the JDK version based on the version you install on your machine_
> 
> Unfortunately on the latest version 2.6.4 the PATH detection issue still persists.

thanks a fuckton!
