### ISSUE TITLE
unable drozer 

### ISSUE THREAD

**Issue by vendanner** [mwrlabs/drozer#161]
"drozer" command  ok. 
![12324353](https://cloud.githubusercontent.com/assets/11388873/8761684/bf1c6a4c-2d90-11e5-8c51-61f38b5602fb.PNG)
but "drozer console" errror!  look at the picture
![1234323](https://cloud.githubusercontent.com/assets/11388873/8761683/b699e5b6-2d90-11e5-88d6-498bb27784de.PNG)
![1213312](https://cloud.githubusercontent.com/assets/11388873/8761685/c79c85bc-2d90-11e5-8f8d-002dca56a9f7.PNG)

**Comment by JosephRedfern** [comment]
Hi @vendanner, did you ever solve this issue? It looks like drozer isn't on your `PYTHONPATH`
