### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by johnconner31** [mwrlabs/drozer#163]
i was using drozer successfully , but suddenly this error is showing while connecting to "[Errno 22] Invalid argument" 
Could you help me to figure out what wrong i am doing?

Same happened on other device too.

Thanks for making wonderful product.

**Comment by johnconner31** [comment]
<img width="642" alt="screen shot 2015-07-31 at 12 29 09 pm" src="https://cloud.githubusercontent.com/assets/13583977/9002299/cceb4a8c-377f-11e5-8f31-98166ed96db6.png">

**Comment by JosephRedfern** [comment]
Hi,

Have you tried running drozer in debug mode (passing the `--debug` flag after `drozer console connect`)? It may provide you with some more information about the error.

Thanks,
Joe

**Comment by johnconner31** [comment]
Hey - thanks for reply.
I run ```drozer console connect --debug```

That's what i got 

```[Errno 35] Resource temporarily unavailable```

So, how to fix this? (my android emulator is running properly)

**Comment by johnconner31** [comment]
Any idea why  it is happening?

**Comment by JosephRedfern** [comment]
Hmm. That's odd. Do you still get the error after a reboot? Can you think of any changes you may have made between drozer working as expected and the problem arising?

**Comment by johnconner31** [comment]
Yes error is same even after reboot. You won't believe i tried every single possibility (reinstall emulator, reboot, reinstall drozer etc.)
On my first device i updated the adt bundles i think and it stop working and on second device when i added second machine on my genymotion emulator.

**Comment by johnconner31** [comment]
So got any idea?

**Comment by johnconner31** [comment]
Hey - If you know what's the reason, could you let me know?

**Comment by JosephRedfern** [comment]
Apologies for the delay, I was away over the weekend. I'll try and have a proper look at this this evening. Can you let me know your OS, the method you used to install drozer, and version of Python you're running please?

**Comment by johnconner31** [comment]
Thanks for reply.
Installing drozer: easy_install ./drozer-2.3.4-py2.7.egg
Python: 2.7.6
OS:  Yosemite 10.10.3

**Comment by JosephRedfern** [comment]
OK, I'm running in the same environment so will hopefully be able to trigger the bug without too much trouble. I'll try and back to you this evening.

**Comment by johnconner31** [comment]
OK, thanks will be waiting.

**Comment by JosephRedfern** [comment]
Right, I've had a quick look, and have some difficulties installing the
Python egg under 10.10.3, but am able to run the latest development version
under Yosemite without any issue.

Could you try following the instructions here:
https://github.com/mwrlabs/drozer/wiki/Running-on-the-edge and see if you
have any more luck? It mainly consists of cloning the relevant repos and
making sure they're on your PYTHONPATH.

**Comment by johnconner31** [comment]
Hi- At the end i decided to re-install the OS and drozer was working fine until i installed these softwares
wireshark,xquartz,utorrent.

Do you have any idea , is these installed softwares could broke drozer functionality?

**Comment by johnconner31** [comment]
Hi Joseph, 

Could you help me to debug the issue? I mean to what broke the functionality again? or installing quartz server for wireshark could impact it in any way? Thanks!

**Comment by amarekano** [comment]
Hi @johnconner31, we've released a new version of Drozer that includes some stability fixes for its dependencies. You can download it at https://github.com/mwrlabs/drozer/releases/tag/2.4.2

Please reopen this issue if you're still having trouble installing/using Drozer. Cheers.
