### ISSUE TITLE
[Errno 36] Operation now in progress

### ISSUE THREAD

**Issue by upgoingstar** [mwrlabs/drozer#166]
I was able to use drozer quite successfully, but then all of a sudden I am receiving this error while trying to connect to console. 

> drozer console connect
Selecting 8aba10d9785a7bdb (Genymotion gg 4.3)
.
.
.
drozer Console (v2.3.4)
[Errno 36] Operation now in progress

I have already forwarded route on port 31415, and drozer agent.apk is turned on. 

Please assist. 

Apart from this, I would like to use this chance to say thanks to folks who have made drozer, it just simplified my life.  :)

**Comment by JosephRedfern** [comment]
Hi @upgoingstar, did you ever resolve this issue?

The "error" (as interpreted by drozer) is probably due to the socket being blocked, perhaps some other process was attempting to communicate with port 31415?
