### ISSUE TITLE
Drozer has trouble finding apk's when ".py" is in path

### ISSUE THREAD

**Issue by emptyaitch** [mwrlabs/drozer#168]
Running drozer in pyenv, located at $HOME/.pyenv .  This causes drozer to be installed in $HOME/.pyenv/versions/&lt;python version 2.7&gt;/.....  When trying to run app.package.manifest, I get the following error: 

drozer could not find or compile a required extension library.

When trying to find the XmlAssetReader.apk, it started the relative_to path at $HOME/.pyenv/versions/..../common/..     When it finds the .py in the full file path, it strips out the ".."  Therefore, it searches for the apk in HOME/.pyenv/versions/..../common/common/XmlAssetReader.apk

**Comment by amarekano** [comment]
Hi @emptyaitch, did you get around to resolving this issue?
