### ISSUE TITLE
Can't get jdk6 to even use drozer

### ISSUE THREAD

**Issue by acaetano** [mwrlabs/drozer#169]
Hi guys,

  i'm not developing modules, but drozer is is returning some strange errors when i ask him to install busybox, send a message to a service, etc. At first there was the whole "invalid parameter" issue, but i managed to solve it by taking the double quotes from the string in the configuration file.

Now it is complaining about a "bad class file magic (cafebabe) or version (0034.0000)". My setup consists of Windows8.1 running drozer 2.3.4 (from the installer) and jdk 1.8.31.

I really saw the #163  issue thread, but how am i supposed to get jdk 6? Oracle has closed the download only to people that have a support account (partners and the like) at its portal. I tried to register one account, but the support portal asks for confirmation from someone that manages the oracle partner account.

**Comment by HenryHoggard** [comment]
If you cannot get Java 6, please use the develop branch of Drozer, which now supports Java 7
