### ISSUE TITLE
Operation not Permitted [Errno1]

### ISSUE THREAD

**Issue by DanoPlurana** [mwrlabs/drozer#175]
Hi

I ve got an [Errno 1] Operation not permitted when trying to connect to my device (drozer console connect). I ve seen there is similar thread already, but it is closed and no solution was given.

Any help would be appreciated.

Cheers

**Comment by HenryHoggard** [comment]
Can you try connect in debug mode and post the results.
`drozer console connect --debug`

**Comment by DanoPlurana** [comment]
The problem is already solved. I needed to reinstall Python in order to get it to work. I tried running console in debug mode, but with no luck. Funny thing is that drozer had worked before it broke and threw me an error I gave in 1st post. 

Thanks for your reply, so far after reinstalling python it's been working like a charm for 2 months :)
Cheers
