### ISSUE TITLE
Version 2.3.4 not tagged on Github?

### ISSUE THREAD

**Issue by ethicalhack3r** [mwrlabs/drozer#177]
I get this output when running Drozer:

```
drozer Console (v2.3.3)
It seems that you are running an old version of drozer. drozer v2.3.4 was
released on 2015-02-20. We suggest that you update your copy to make sure that
you have the latest features and fixes.
```

I can see that the 2.3.4 downloads are available on https://www.mwrinfosecurity.com/products/drozer/ but not on Github's releases https://github.com/mwrlabs/drozer/releases

Personally, I want this to see the changes (changelog) between version 2.3.3 and 2.3.4, but probably best tagging a release here for best practice anyway.

**Comment by HenryHoggard** [comment]
2.3.4 is now tagged on Github. Future releases will be accompanied with full changelog too.

Thanks,
Henry
