### ISSUE TITLE
drozer could not find or compile a required extension library on windows 7

### ISSUE THREAD

**Issue by harris2015** [mwrlabs/drozer#179]
I install drozer on windows7,and set the java path as follows:
java=C:\Program Files\Java\jdk1.6.0_43\bin\java.exe
javac="C:\Program Files\Java\jdk1.6.0_43\bin\javac.exe"

when I run the command:run scanner.provider.finduris -a com.tencent.mm
it shows:
Scanning com.tencent.mm...
"C:\Program Files\Java\jdk1.7.0_80\bin\javac.exe" -cp D:\dz\drozer\lib\drozer\li
b\android.jar D:\dz\drozer\lib\drozer\modules\common\ZipUtil.java
D:\dz\drozer\lib\drozer\lib\dx.bat --dex --output D:\dz\drozer\lib\drozer\module
s\common\4a78a7a38b67b985beccf6efac92375b.apk D:\dz\drozer\lib\drozer\modules\co
mmon\ZipUtil.class

trouble processing:
bad class file magic (cafebabe) or version (0033.0000)
...while parsing D:/dz/drozer/lib/drozer/modules/common/ZipUtil.class
...while processing D:/dz/drozer/lib/drozer/modules/common/ZipUtil.class
1 warning
no classfiles specified
drozer could not find or compile a required extension library.

so pls give some advice.Thanks very much

**Comment by airvijair** [comment]
Am also facing same issue.

C:\Java\jdk1.7.0_79\bin\javac.exe -cp C:\drozer\lib\drozer\lib\android.jar ZipUtil.java
C:\drozer\lib\drozer\lib\dx.bat --dex --output 4a78a7a38b67b985beccf6efac92375b.apk ZipUtil.class

trouble processing:
bad class file magic (cafebabe) or version (0033.0000)
...while parsing ZipUtil.class
...while processing ZipUtil.class
1 warning
no classfiles specified
drozer could not find or compile a required extension library.

Could please some one help us...

**Comment by biernat** [comment]
Hi, you have to install Java 1.6 and set the path in the .drozer_config file.
