### ISSUE TITLE
 sh: /data/data/com.mwr.dz/su: not found

### ISSUE THREAD

**Issue by WangYeOtw** [mwrlabs/drozer#181]
run scanner.misc.writablefiles --privileged /data/data/com.sina.weibo
 sh: /data/data/com.mwr.dz/su: not found

**Comment by HenryHoggard** [comment]
Is the device rooted? A "su" binary needs to be present in either of the following locations:
```
/system/bin/su
/system/xbin/su
/data/data/com.mwr.dz/su
```
