### ISSUE TITLE
drozer could not find or compile a required extension library.

### ISSUE THREAD

**Issue by Droidmannn** [mwrlabs/drozer#183]
As mentioned in the https://github.com/mwrlabs/drozer/issues/147 i tried with the latest package i got the error as mentioned in https://github.com/mwrlabs/drozer/issues/155. I am using MAC 10.10.5.

So i made the changes for pyopenssl-0.15 support, and created a new pull request. I downloaded the zip and installed drozer. Still I am getting "drozer could not find or compile a required extension library." when i execute
run scanner.provider.finduris -a com.<packagename>

Also i tried with JDK 6 still it doesn't work.
Please help!!!

**Comment by Droidmannn** [comment]
Can someone please help what I am missing here?

**Comment by HenryHoggard** [comment]
Please run the following command then rebuild Drozer:
`make apks`
