### ISSUE TITLE
Redirect Output to File

### ISSUE THREAD

**Issue by smhome** [mwrlabs/drozer#185]
Every time I try to redirect the output of a drozer command to a local file my drozer console disconnects. The specified file is created but without any content.

Command example:
dz> run app.package.list > output.txt

**Comment by JosephRedfern** [comment]
Hi @smhome,

Can you post the output having run drozer in verbose mode, using the `-v` flag?

Thanks.

**Comment by smhome** [comment]
Hi @JosephRedfern,

Could you name the exact command that can be run with `-v`?

**Comment by JosephRedfern** [comment]
@smhome apologies, I meant `--debug` -- so start drozer using `drozer console connect --debug`.

**Comment by smhome** [comment]
Ok, for any reason it works now after reinstalling drozer.

Thans @JosephRedfern anyway!
