### ISSUE TITLE
Error  Messages while accessing drozer

### ISSUE THREAD

**Issue by arunsunkumar** [mwrlabs/drozer#186]
Hi,

I am facing below issue when running drozer in Win 7 64 Bit O.S:

dz> run app.package.manifest org.owasp.goatdroid.herdfinancial

Could not find javac. Please ensure that it is installed and on your PATH.

If this error persists, specify the path in the ~/.drozer_config file:
    [executables]
    javac = C:\path\to\javac
Could not find javac on your PATH.

I have created .drozer_config.txt file under c:/users<username>/

same issue i was facing when executing drozer.bat console connect but it got resolved when including the below lines in configuration.py file located in C:\Program Files\drozer\Lib\drozer 

 #check the library
		
	if name == 'java': 
		path = 'c:\Program Files\Java\jdk1.6.0_45\bin'
	
	else:
		path = cls.library(name)

but unable to resolve for javac path ....

Kindly do the needful.....

**Comment by HenryHoggard** [comment]
What are the contents of your drozer config?

**Comment by dinasaif** [comment]
create file in your root called it .drozer_config.txt 
Then write in it the path to java & javac for example:
[executables]
java = C:\Program Files\Java\jdk1.6.0_45\bin\java.exe
javac = C:\Program Files\Java\jdk1.6.0_45\bin\javac.exe
Then try drozer
