### ISSUE TITLE
Java Error in Drozer

### ISSUE THREAD

**Issue by arunsunkumar** [mwrlabs/drozer#188]
Hi All,

I am facing the below issue:

dz> run app.package.manifest org.owasp.goatdroid.herdfinancial
C:\Program Files\Java\jdk1.6.0_45\bin\javac.exe -cp C:\Program Files\drozer\lib\drozer\lib\android.jar XmlAssetReader.java
javac: invalid flag: Files\Java\jdk1.6.0_45\bin\javac.exe

Kindly do the needfull.....

**Comment by dinasaif** [comment]
I have the same problem please how can you solve that?
