### ISSUE TITLE
List and Other commands are not working in drozer v2.3.4

### ISSUE THREAD

**Issue by smitbshah92** [mwrlabs/drozer#189]
Hello,

After successfully installing drozer apk in virtual maching and starting embedded server, I am able to connect drozer console using adb but list and other commands like run and all modules are not working. Please let me know what I am doing wrong?
![drozer problem](https://cloud.githubusercontent.com/assets/17097532/12866827/01f4058a-cd02-11e5-8154-c7579c200664.JPG)

**Comment by HenryHoggard** [comment]
Set the Java path in the .drozer_config file.

```
[executables]
java = C:\path\to\java
```

**Comment by smitbshah92** [comment]
Thank you Henry for pointing this out. Actually I am using a tool named Appie for Android App Pentesting. The issue was with installation of Appie and not with drozer. It was needed to be installed in C:/root folder and not in C:/Program Files/ which was my mistake. Now drozer is working perfectly. Thanks. :)

**Comment by ViktorijaAdo** [comment]
I'm having the same issue now. 
![image](https://user-images.githubusercontent.com/24551172/38132825-613e8ef8-3415-11e8-8fbb-41a4d14799b2.png)
Not sure what may be wrong
