### ISSUE TITLE
[Question] Difference among Agent APKs

### ISSUE THREAD

**Issue by mrpinghe** [mwrlabs/drozer#192]
Hey guys,

This is more of a question, rather than an issue. I see you guys now have a standard-agent.apk and a rogue-agent.apk in your source, and both have different MD5 than the agent.apk you have on your website and referenced throughout the user guide pdf.

The question is... what's the difference between these three apks?

Thanks!

**Comment by HenryHoggard** [comment]
Standard-agent.apk has a GUI whereas Rogue-agent.apk doesn't. We will get the MD5Sums fixed.

Thanks
