### ISSUE TITLE
egg file won't work due to bug in pyOpenSSL

### ISSUE THREAD

**Issue by mrpinghe** [mwrlabs/drozer#194]
Hi,

There is a known bug with pyOpenSSL 0.13 (https://github.com/sumanj/frankencert/issues/4) compiling against newer version of OpenSSL, and this has been resolved in pyOpenSSL 0.14. Since the egg file to install drozer explicitly depends on 0.13, this bug with pyOpenSSL is preventing successful installation of drozer.

Could you guys do some magic, maybe update the dependency, to resolve this, so I can install drozer on machines with newer OpenSSL?

Thanks!

**Comment by HenryHoggard** [comment]
This has already been fixed in the develop branch. You can build from the develop branch to receive this fix.

**Comment by youdy3000** [comment]
Hi @HenryHoggard, thanks for answering.

@mrpinghe, how did you go about installing the Drozer dev branch on a Mac with El Capitan?

I was following the instructions in the MWR user guide.  I get the OpenSSL issue you mentioned.  I am following the instructions on:
https://labs.mwrinfosecurity.com/system/assets/502/original/mwri_drozer-users-guide_2013-07-25.pdf

I spent ages on this (setup a VM with Windows which works & installed MacPorts to install a newer version of OpenSSL libraries).  The following article showed the underlying issue http://karl.kornel.us/2015/12/el-capitan-need-openssl-install-macports/

**Comment by mrpinghe** [comment]
Hi @youdy3000 It's been a while since I did it, but it did take quite some tweaking from the "develop" branch. I remember doing the following (some of them may not be necessary)
- check out the develop branch and make it
- used an older version of the Makefile https://github.com/mwrlabs/drozer/commit/7b15b980b0b3a5baa12c49f524483e8d7ac3eef4 and found the deleted code, which creates the .egg file
- a lot of fixing based on error messages. I do remember having to install some dependencies, so make sure you easy_install the dependencies according to the INSTALLING file

I'm on Yosemite, although I don't think that matters. Feel free to post any error messages occurred (potentially as a separate thread?). Maybe I or drozer folks can help?
