### ISSUE TITLE
drozer agent has stopped!

### ISSUE THREAD

**Issue by murugant** [mwrlabs/drozer#197]
Everytime I try to scan the package for uris using, run.scanner.provider.finduris -a, the phone says,
 "Unfortunately, drozer agent has stopped working" 
 Kindly give me some insight of how to get through this error. 
![drozererror](https://cloud.githubusercontent.com/assets/9444807/13829637/5d402560-ebc8-11e5-872a-4744b87da929.jpg)

**Comment by HenryHoggard** [comment]
Please run drozer in debug mode and respond with the debug output.

```
$ drozer console connect --debug
dz> run scanner.provider.finduris
```

In addition to this please capture the device logs using adb and post here.
`$ adb logcat > logs.txt`

**Comment by murugant** [comment]
Thanks for answering. I have attached them here.
![debugreport](https://cloud.githubusercontent.com/assets/9444807/13843992/4a0d971a-ec37-11e5-98a7-dc74e9fef118.jpg)
[logs.txt](https://github.com/mwrlabs/drozer/files/177683/logs.txt)

**Comment by JosephRedfern** [comment]
The screenshot would appear to be caused by a different problem - you're not passing the `-a` flag before `com.android.mms`. That shouldn't cause the agent to crash though!

**Comment by murugant** [comment]
I have tried that too.

![drozerdebug2](https://cloud.githubusercontent.com/assets/9444807/13844266/21746d4a-ec39-11e5-921b-8d565cc669c8.jpg)

**Comment by HenryHoggard** [comment]
As this is an issue with the agent crashing, you will need to provide logcat output for us to debug this.

**Comment by HenryHoggard** [comment]
Cause of crash here. It appears to be missing libmstring.so, this should be packaged with the Drozer apk. @murugant  what version of the Drozer APK are you using?

```

--------- beginning of crash

03-16 22:22:34.564  4673  7801 E AndroidRuntime: FATAL EXCEPTION: Thread-255

03-16 22:22:34.564  4673  7801 E AndroidRuntime: Process: com.mwr.dz:remote, PID: 4673

03-16 22:22:34.564  4673  7801 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mwr.dz-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mwr.dz-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libmstring.so"

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at com.mwr.jdiesel.util.Strings.<clinit>(Strings.java:6)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:324)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:285)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at com.mwr.jdiesel.reflection.Reflector.resolve(Reflector.java:138)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at com.mwr.jdiesel.api.handlers.ReflectionMessageHandler.handleResolve(ReflectionMessageHandler.java:193)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at com.mwr.jdiesel.api.handlers.ReflectionMessageHandler.handle(ReflectionMessageHandler.java:66)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at com.mwr.jdiesel.api.sessions.Session.handleMessage(Session.java:35)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at com.mwr.jdiesel.connection.AbstractSession.run(AbstractSession.java:76)

03-16 22:22:34.564  4673  7801 E AndroidRuntime: 	at com.mwr.jdiesel.api.sessions.Session.run(Session.java:42)
```

**Comment by murugant** [comment]
I am using drozer agent v2.3.3

**Comment by HenryHoggard** [comment]
Can you try with this and tell me if you still get the crash.
https://labs.mwrinfosecurity.com/system/assets/934/original/drozer-agent-2.3.4.apk

**Comment by HenryHoggard** [comment]
If you are using an x86-64 device then that may be the issue, It doesn't look like we have compile libmstring for that architecture.

**Comment by JosephRedfern** [comment]
Hmm, looking at the logcat output it seems that it's a Motorolla Moto X which has a Snapdragon S4 so shouldn't cause any problems re: architecture!

**Comment by murugant** [comment]
@HenryHoggard v2.3.4 is working fine. I am now able to run the query :) thank u so much!
