### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by 2048li** [mwrlabs/drozer#199]
hi, when i run the command"run app.provider.query content://*****", it shows me the "unknown" error.
does this command in drozer limited to special application?
thanks.

**Comment by HenryHoggard** [comment]
Please run drozer in debug mode and post result.

`$ drozer console connect --debug
dz> run app.provider.query content://`

**Comment by 2048li** [comment]
Thanks first. I use debug mode and rerun, it shows "reflectionexception :could not get a contentproviderclient for **provider".

**Comment by HenryHoggard** [comment]
Without know the application and provider you are trying to query, we cannot debug this. Its likely to be an issue with the application you are trying to query, rather than Drozer.

**Comment by HenryHoggard** [comment]
This issue has been closed due to inactivity. If you are still experiencing this issue, please comment or reopen.
