### ISSUE TITLE
app.provider.read content://...: unabletoopenfileexception

### ISSUE THREAD

**Issue by 2048li** [mwrlabs/drozer#200]
hi,
excuse me. I use the command "run app.provider.read content://.....", it shows "unabletoopenfileexception:it was not possible to open the file represented by content://.....",
but I can see the read and write permission of this provider is null using the "run app.provider.info -a packagename". Now that the permission is null, why cannot read the provider? Any ideas?

Thanks.

**Comment by HenryHoggard** [comment]
Is it exported?

**Comment by HenryHoggard** [comment]
Without the application or file you are trying to open we can't help you.
