### ISSUE TITLE
[Errno 2] No such file or directory [win10+python 3.5]

### ISSUE THREAD

**Issue by yb184007** [mwrlabs/drozer#204]
encounter below issue
not sure what happened, and no results from google...need your help, thank you!
![image](https://cloud.githubusercontent.com/assets/18525655/14596525/992180b8-0579-11e6-80da-e95c2e81065d.png)

my laptop is thinkpad with windows 10
jdk/jre version 1.8u77
python version 3.5

update 20160524:
i think there should be an '\' between bin and javac in my screenshot pic...but dont know how to resolve.
environment variables　already correctly set up, can run java and javac directly via CMD
other functions work fine, only this finduris have problem....please help me

**Comment by HenryHoggard** [comment]
Thanks for the bug report.

Did you compile Drozer from source or did you use the .exe?

**Comment by HenryHoggard** [comment]
Closed due to no response. Please reopen if this is still an issue.

**Comment by r3dw4x** [comment]
I am facing the same problem. I didn't compile it I used .exe

**Comment by HenryHoggard** [comment]
Hi @r3dw4x  what is the contents of your drozer config file?

**Comment by amarekano** [comment]
Closed due to no response. Please reopen if this is still an issue.
