### ISSUE TITLE
Unable to load webcontentresolver.py module

### ISSUE THREAD

**Issue by pentagramz** [mwrlabs/drozer#207]
Hi ,

I am Unable to load webcontentresolver.py module.

Please help me
![drozer1](https://cloud.githubusercontent.com/assets/7072014/15673753/590b543c-2756-11e6-8ebb-ad04297b34a2.JPG)

**Comment by pentagramz** [comment]
https://github.com/dnet/mercury/blob/master/client/merc/modules/auxiliary/webcontentresolver.py

**Comment by HenryHoggard** [comment]
Could you give more information, is this a standard install of Drozer? The source file you linked is from Mercury in 2012, and wouldn't be compatible with the version of Drozer you are running.

Please rerun Drozer in debug mode, this will provide us with more detailed drozer logs.

`$ drozer console connect --debug`
