### ISSUE TITLE
How to install drozer in mac osx

### ISSUE THREAD

**Issue by Murthysagi** [mwrlabs/drozer#208]
can u help me how to install drozer module in mac osx

**Comment by HenryHoggard** [comment]
To learn how to install Drozer modules please visit page 20 of this user guide.

https://labs.mwrinfosecurity.com/system/assets/502/original/mwri_drozer-users-guide_2013-07-25.pdf

**Comment by metall0id** [comment]
This is the latest user manual: https://labs.mwrinfosecurity.com/assets/BlogFiles/mwri-drozer-user-guide-2015-03-23.pdf
