### ISSUE TITLE
question about permissions

### ISSUE THREAD

**Issue by javixeneize** [mwrlabs/drozer#209]
Hi

I am trying to run a content provider, and it says that i don't have the right permission (android.permission.test), being this permission something i have created inside my application
I have modified drozer agent apk manifest and adding this permission
 uses-permission android:name="android.permission.test,  rebuilding with apktool and signing with my own key
Once i push it to the device and execute this new drozer with this permission, i continue having the same error
Am i doing right giving this permission to this apk or have i understood it totally wrong?
Thanks

**Comment by HenryHoggard** [comment]
You can use the following to define or give permissions to the Drozer agent:
`drozer agent build --permission <permission>
`drozer agent build --define-permission <permission>
