### ISSUE TITLE
Drozer Android application always crashes on device upon trying to run the command "run scanner.provider.finduris -a com.fexample.xxx.xxx"

### ISSUE THREAD

**Issue by krishachetan89** [mwrlabs/drozer#210]
Steps:
1. Launch drozer app
2. connect to device and start drozer
3. issue the command run scanner.provider.finduris -a com.android.xxxx.xxx and observe
4. logs attached

Observation: Drozer agent always crashes on the mobile device and unable to obtain the results

> `E/AndroidRuntime( 5350): FATAL EXCEPTION: Thread-465
> 
> E/AndroidRuntime( 5350): Process: com.mwr.dz:remote, PID: 5350
> 
> E/AndroidRuntime( 5350): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mwr.dz-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libmstring.so"
> 
> E/AndroidRuntime( 5350):  at java.lang.Runtime.loadLibrary(Runtime.java:366)
> 
> E/AndroidRuntime( 5350):  at java.lang.System.loadLibrary(System.java:988)
> 
> E/AndroidRuntime( 5350):  at com.mwr.jdiesel.util.Strings.<clinit>(Strings.java:6)
> 
> E/AndroidRuntime( 5350):  at java.lang.Class.classForName(Native Method)
> 
> E/AndroidRuntime( 5350):  at java.lang.Class.forName(Class.java:309)
> 
> E/AndroidRuntime( 5350):  at java.lang.Class.forName(Class.java:273)
> 
> E/AndroidRuntime( 5350):  at com.mwr.jdiesel.reflection.Reflector.resolve(Reflector.java:138)
> 
> E/AndroidRuntime( 5350):  at com.mwr.jdiesel.api.handlers.ReflectionMessageHandler.handleResolve(ReflectionMessageHandler.java:193)
> 
> E/AndroidRuntime( 5350):  at com.mwr.jdiesel.api.handlers.ReflectionMessageHandler.handle(ReflectionMessageHandler.java:66)
> 
> E/AndroidRuntime( 5350):  at com.mwr.jdiesel.api.sessions.Session.handleMessage(Session.java:35)
> 
> E/AndroidRuntime( 5350):  at com.mwr.jdiesel.connection.AbstractSession.run(AbstractSession.java:76)
> 
> E/AndroidRuntime( 5350):  at com.mwr.jdiesel.api.sessions.Session.run(Session.java:42)
> [drozercrash.txt](https://github.com/mwrlabs/drozer/files/341031/drozercrash.txt)
> `

**Comment by dinasaif** [comment]
try to write run scanner.provider.finduris com.android.xxxx.xxx

**Comment by HenryHoggard** [comment]
Hi @krishachetan89, what device and Android version are you using.

**Comment by krishachetan89** [comment]
Device used Nexus 5 , Android version 5.1.1

**Comment by amarekano** [comment]
Hi @krishachetan89, could you give us details of your host configuration.
The operating system, the jdk version installed and the version of drozer being used.

**Comment by amarekano** [comment]
Closed due to lack of response. Please reopen this issue if you're still unable to get drozer working.
