### ISSUE TITLE
path not found: android.jar ziputil.java

### ISSUE THREAD

**Issue by PareshParmar** [mwrlabs/drozer#213]
hi,
Os: windows 8
after solving one issue (java/javac path),
 i got another.
`run app.provider.finduri com.mobile.app`
error

```
Scanning com.mobile.app...
C:\Program Files\Java\jdk1.7.0_79\javac.exe -cp C:\Program Files\drozer\lib\drozer\lib\android.jar ZipUtil.java
[Errno 2] No such file or directory

```

i read few issues here, but didnt help .
Thanks

**Comment by dinasaif** [comment]
I already solved it by take copy from java file and write in configuration.py file (drozer\Lib\drozer\drozer) the new path for javac:
#check the library
path = cls.library(name)

    #is the required exe available on the PATH?
    if path == None and cls.get("executables", name) == None:
       path = 'D:\\Java\\jdk1.6.0_45\\bin\\javac.exe'


    if path == None:
        path = cls.get("executables", name)

    if path == None or path == "":
        sys.stderr.write("Could not find %s. Please ensure that it is installed and on your PATH.\n\nIf this error persists, specify the path in the ~/.drozer_config file:\n\n    [executables]\n    %s = %s\n" % (name, name, platform.system() == "Windows" and "C:\\path\\to\\" + name or "/path/to/" + name))

    return path

**Comment by amarekano** [comment]
HI @PareshParmar, did you get around to solving this issue?

please feel free to reopen this issue if you're still unable to use drozer.
