### ISSUE TITLE
How to make dynamic analysis????

### ISSUE THREAD

**Issue by dinasaif** [mwrlabs/drozer#214]
I want to make dynamic analysis on android applications to extract features from it and get report.
For example if app send SMS in the background I want to know the number of recipient and the content of the SMS  .
I mean I want actions like : action sendnet is the action that sends data over the network,
 action phonecalls is the action that makes a phone call, 
and action sendsms is the action that sends SMS messages.

**Comment by HenryHoggard** [comment]
You can use the module app.broadcast.sniff to monitor intents:

```
  dz> run app.broadcast.sniff --action android.intent.action.BATTERY_CHANGED
    [*] Broadcast receiver registered to sniff matching intents
    [*] Output is updated once a second. Press Control+C to exit.
    Action: `android.intent.action.BATTERY_CHANGED
  Raw: Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) }
    Extra: technology=Li-ion (java.lang.String)
    Extra: icon-small=17303411 (java.lang.Integer)
    Extra: health=2 (java.lang.Integer)
    Extra: online=4 (java.lang.Integer)
    Extra: status=2 (java.lang.Integer)
    Extra: plugged=2 (java.lang.Integer)
    Extra: present=true (java.lang.Boolean)
```

Simply replace the battery changed intent to the SMS or phone call intent.

**Comment by Kheddaoui-amine** [comment]
dinasaif,
can you help in my project its about analyse APIS from dex files? please

**Comment by dinasaif** [comment]
Do you want to make static analysis only??
please , Send your request with details and I will help you

**Comment by dinasaif** [comment]
If you want API only this is avery good jar called DERG
https://github.com/ylimit/derg
you can get json file And APIS will be under name :method_lib
all method_lib are APIS
If you want any thing else you can send me : dinasaif1984@gmail.com
