### ISSUE TITLE
Cannot download windows installer. 404 not found in mwrinfosecurity

### ISSUE THREAD

**Issue by ciobanualexandru13** [mwrlabs/drozer#216]
### Steps to reproduce
Go to labs.mwrinfosecurity, tools section. Cannot download neither on Linux neither on Windos

### Expected behaviour
Should be able to download 

### Actual behaviour
404 not found

### Environment

**Operating system**:

**Java Version:**

**Android Version:**

**Drozer Version:** 

**Install Method:** Built from source/.deb/.exe/..

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by JosephRedfern** [comment]
I see this problem too. As a temporary workaround, removing /system from the URL (i.e. https://labs.mwrinfosecurity.com/system/assets/933/original/drozer-2.3.4.tar.gz becomes https://labs.mwrinfosecurity.com/assets/933/original/drozer-2.3.4.tar.gz) seems to solve the issue. 

@HenryHoggard, can this be fixed?

**Comment by ciobanualexandru13** [comment]
Thanks @JosephRedfern !

**Comment by HenryHoggard** [comment]
Yes, the new website migration lost all the Drozer uploads. I will reupload as soon as I can.

**Comment by sratatata** [comment]
Hi, same with debian: 
https://labs.mwrinfosecurity.com/system/assets/931/original/drozer_2.3.4.deb

404

**Comment by HenryHoggard** [comment]
The missing install files can be found here:

https://github.com/mwrlabs/drozer/releases/tag/2.3.4
