### ISSUE TITLE
Building from Source : no module named drozer

### ISSUE THREAD

**Issue by amirbijani** [mwrlabs/drozer#218]
when trying to build from the source  `  python setup.py build`
      is gets this error :

```
Traceback (most recent call last):
File "setup.py", line 6, in <module>
from drozer import meta
ImportError: No module named drozer


 
```

is that one depending on : [https://github.com/mwrlabs/drozer/issues/217](url) ????

**Comment by dmitvitalii** [comment]
Same issue. Have tried to use some old commits or a master branch, but didn't work. Also tried an installation way from the INSTALL file, but there is no drozer-2.3.0-py2.7.egg file.

**Comment by HenryHoggard** [comment]
Please use the provided issue template for us to debug your issue.
