### ISSUE TITLE
Sieve.apk dead download links

### ISSUE THREAD

**Issue by BigNoseSec** [mwrlabs/drozer#219]
Sieve.apk download is broken on the main site and in user guide PDF.

https://labs.mwrinfosecurity.com/tools/drozer/ (on bottom of page links to v)

https://labs.mwrinfosecurity.com/system/assets/380/original/sieve.apk (404)

**Comment by HenryHoggard** [comment]
The downloads were lost in migration to the new website. We are working to fix this as soon as possible.

**Comment by rajivvishwa** [comment]
Any luck? None of files linked in the Drozer website are not accessible. Please fix or provide alternate location from where we can download. Adding the files in github will also work.

**Comment by HenryHoggard** [comment]
The drozer download links can be found on Github under releases. (https://github.com/mwrlabs/drozer/releases)

**Comment by jgimer** [comment]
I cannot find a location to download sieve.apk under releases on GitHub. you can download the various releases of drozer and the agent.apk at this location, but there isn't anything related to sieve. The tarballs and zip archives that are downloadable at this location do not include a sieve.apk.
