### ISSUE TITLE
linux install drozer error:  ImportError: No module named drozer

### ISSUE THREAD

**Issue by wlc520123** [mwrlabs/drozer#222]
### Steps to reproduce
1. log in ubuntu 12.04 as user, not root
2.run command :
git clone https://github.com/mwrlabs/drozer/
cd drozer
python setup.py build

### Expected behaviour
should run successfully

### Actual behaviour
run error: no drozer module:
SPREADTRUM\jyin.li@tj05002pcu:~/drozer$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from drozer import meta
ImportError: No module named drozer

### Environment

**Operating system**:
	Ubuntu 12.04.2 LTS   x86_64
**Java Version:**
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Android Version:**
6.0
**Drozer Version:** 
git clone at 14/9/2016

**python version:**
Python 2.7.3

**Comment by HenryHoggard** [comment]
**Duplicate Issue:** https://github.com/mwrlabs/drozer/issues/148
**Further Reading:** https://github.com/mwrlabs/drozer/wiki/Running-on-the-edge

You need to set your environment variables up for drozer.

`echo \$PYTHONPATH=$PYTHONPATH:/path/to/drozer/src >> ~/.bash_profile`

**Comment by ricardozv** [comment]
this not function for me
