### ISSUE TITLE
sieve apk file is not available 

### ISSUE THREAD

**Issue by krbuk2013** [mwrlabs/drozer#223]
### Steps to reproduce
1. https://www.mwrinfosecurity.com/system/assets/380/original/sieve.apk
2. sieve apk file is not available 
### Expected behaviour

sieve apk file should be available 
### Actual behaviour

sieve apk file is not available 
### Environment

**Operating system**:

**Java Version:**

**Android Version:**

**Drozer Version:** 

**Install Method:** Built from source/.deb/.exe/..
### Drozer Config

```
Contents of ~/.drozer_config
```
### Drozer Error Logs

```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```
### ADB Logs

```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by ZapApp** [comment]
The drozer user guide uses sieve app for all examples. I hope it will be available soon.

**Comment by ZapApp** [comment]
It would be really helpful if sieve.apk is provided since drozer documentation is using it extensively

**Comment by McLovi9** [comment]
Please provide link to sieve apk. I'm new to drozer and there is a lot of tuts refering to sieve apk but download link is down.

**Comment by chengteck** [comment]
Hi there. Is there any update on this issue?
The download link to sieve apk is still down.

**Comment by HenryHoggard** [comment]
Please download sieve from here:

https://github.com/mwrlabs/drozer/releases/download/2.3.4/sieve.apk

**Comment by krbuk2013** [comment]
@HenryHoggard Thank you very much
