### ISSUE TITLE
easy_install d:\drozer-2.3.4-py2.7.egg, drozer command could not find

### ISSUE THREAD

**Issue by wlc520123** [mwrlabs/drozer#224]
### Steps to reproduce

1.install paython 2.7
2.install vc compile for python 2.7
3.easy_install --allow-hosts pypi.python.org protobuf
4.easy_install twisted==10.2.0
5.easy_install d:\drozer-2.x.x-py2.7.egg
Then run drzoer command in cmd.
### Expected behaviour

return :
$ drozer 
usage: drozer [COMMAND] 
Run `drozer [COMMAND] --help` for more usage information.
### Actual behaviour

"drozer"command could not find
### Environment

**Operating system**:
win 7 64bits
**Java Version:**
java version: 1.7.
**Android Version:**

**Drozer Version:** 
2.3.4, download from https://labs.mwrinfosecurity.com/tools/drozer/, drozer (Python .egg)

**Install Method:** Built from source/.deb/.exe/..
### Drozer Config

```
Contents of ~/.drozer_config
```
### Drozer Error Logs

```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```
### ADB Logs

```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by HenryHoggard** [comment]
Can you post the error log please.

**Comment by wlc520123** [comment]
easy_install command run ok:
![easy_install](https://cloud.githubusercontent.com/assets/11263857/18771304/71d4a1f2-8170-11e6-8f94-02a4209e10ab.png)

but drozer command could not find:
![drzoer](https://cloud.githubusercontent.com/assets/11263857/18771324/9297664a-8170-11e6-88b2-fa288c3bdc5f.png)

in python command terminal, run "help ('modules'), drozer is in the result:
![drzoer](https://cloud.githubusercontent.com/assets/11263857/18771372/03bff4e0-8171-11e6-988c-35a60072c3f5.png)
![drozerin](https://cloud.githubusercontent.com/assets/11263857/18771376/0af4c326-8171-11e6-8096-992c23dcc28c.png)

**Comment by amarekano** [comment]
Hi @wlc520123, In order to run drozer you would have to run the following command:
python.exe D:\python27\Scripts\drozer

Also, we've released a newer and recommended version of drozer which includes a number of stability fixes. You can download this at https://github.com/mwrlabs/drozer/releases/tag/2.4.2

Please reopen this issue if you still have trouble installing/using drozer.
