### ISSUE TITLE
drozer agent build leads to nullpointerexception

### ISSUE THREAD

**Issue by smhome** [mwrlabs/drozer#227]
When running:
`drozer agent build`
following exception occurs:

> Exception in thread "main" java.lang.NullPointerException
>   at java.io.Writer.write(Writer.java:140)
>   at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
>   at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
>   at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
>   at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
>   at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
>   at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
>   at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:130)
>   at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:144)
>   at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
>   at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:218)
>   at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:115)
>   at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)
>   at brut.apktool.Main.cmdDecode(Main.java:146)
>   at brut.apktool.Main.main(Main.java:77)
> could not unpack standard-agent
### Environment

**Operating system**: Kali Rolling

**Java Version:** java version "1.6.0_45"

**Drozer Version:** 
branch develop up-to-date

**Comment by HenryHoggard** [comment]
Is this drozer 2.3.4 or 2.4.0?

**Comment by smhome** [comment]
Right. I installed 2.4.0 instead of 2.3.4.

No nullpointerexception anymore, but still getting:
could not unpack standard-agent

**Comment by HenryHoggard** [comment]
`drozer agent build` in Drozer 2.4.0 makes use of APKTool 2.0. APKTool no longer supports Java 1.6, could you try this using Java 1.7 or 1.8?

**Comment by smhome** [comment]
tried with both.. same problem:
$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
$ javac -version
javac 1.7.0_80
$apktool
Apktool v2.2.1 - a tool for reengineering Android apk files
...
$ drozer agent build
could not unpack standard-agent

**Comment by HenryHoggard** [comment]
I cant reproduce this issue. I just tried using the same setup as you and it works.

**Comment by HenryHoggard** [comment]
Hi @smhome  are you still experiencing this issue?

**Comment by HenryHoggard** [comment]
Hi @smhome are you still experiencing this issue? Can you please try Drozer 2.4.1

**Comment by amarekano** [comment]
Hi @smhome, drozer uses a bundled apktool in order to build the agent. It doesn't use locally installed instances of apktool.

Please use our latest drozer release and reopen this issue if you're still having trouble building the agent.
The latest release can be found at https://github.com/mwrlabs/drozer/releases/tag/2.4.2
