### ISSUE TITLE
tools error 

### ISSUE THREAD

**Issue by Any3ite** [mwrlabs/drozer#232]
how can i do it ? 

###$ sudo easy_install --allow-hosts pypi.python.org protobuf==2.4.1
Password:
Searching for protobuf==2.4.1
Best match: protobuf 2.4.1
Processing protobuf-2.4.1-py2.7.egg
protobuf 2.4.1 is already the active version in easy-install.pth

Using /Library/Python/2.7/site-packages/protobuf-2.4.1-py2.7.egg
Processing dependencies for protobuf==2.4.1
Finished processing dependencies for protobuf==2.4.1
###$  sudo easy_install twisted==10.2.0 
Searching for twisted==10.2.0
Best match: Twisted 10.2.0
Processing Twisted-10.2.0-py2.7-macosx-10.12-intel.egg
Twisted 10.2.0 is already the active version in easy-install.pth
Installing cftp script to /usr/local/bin
Installing ckeygen script to /usr/local/bin
Installing conch script to /usr/local/bin
Installing lore script to /usr/local/bin
Installing mailmail script to /usr/local/bin
Installing manhole script to /usr/local/bin
Installing mktap script to /usr/local/bin
Installing pyhtmlizer script to /usr/local/bin
Installing tap2deb script to /usr/local/bin
Installing tap2rpm script to /usr/local/bin
Installing tapconvert script to /usr/local/bin
Installing tkconch script to /usr/local/bin
Installing trial script to /usr/local/bin
Installing twistd script to /usr/local/bin

Using /Library/Python/2.7/site-packages/Twisted-10.2.0-py2.7-macosx-10.12-intel.egg
Processing dependencies for twisted==10.2.0
Finished processing dependencies for twisted==10.2.0
demaxiya:mobile any3ite$ sudo easy_install ./drozer-2.3.4-py2.7.egg
Processing drozer-2.3.4-py2.7.egg
removing '/Library/Python/2.7/site-packages/drozer-2.3.4-py2.7.egg' (and everything under it)
creating /Library/Python/2.7/site-packages/drozer-2.3.4-py2.7.egg
Extracting drozer-2.3.4-py2.7.egg to /Library/Python/2.7/site-packages
Removing drozer 2.4.1 from easy-install.pth file
Adding drozer 2.3.4 to easy-install.pth file
Installing drozer script to /usr/local/bin
Installing drozer-complete script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/drozer-2.3.4-py2.7.egg
Processing dependencies for drozer==2.3.4
Finished processing dependencies for drozer==2.3.4
###$ drozer console connect
Traceback (most recent call last):
  File "/usr/local/bin/drozer", line 4, in <module>
    __import__('pkg_resources').run_script('drozer==2.3.4', 'drozer')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/drozer-2.3.4-py2.7.egg/EGG-INFO/scripts/drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
  File "/Library/Python/2.7/site-packages/drozer-2.3.4-py2.7.egg/drozer/cli/console.py", line 11, in <module>
    logger.addStreamHandler()
  File "/Library/Python/2.7/site-packages/drozer-2.3.4-py2.7.egg/mwr/common/logger.py", line 32, in addStreamHandler
    addHandler(logging.StreamHandler(stream=sys.stdout))
TypeError: __init__() got an unexpected keyword argument 'stream'

**Comment by HenryHoggard** [comment]
What is the question?

**Comment by amarekano** [comment]
Hi @Any3ite, could you try installing drozer 2.4.2 and let us know if you face the same issue. You can find the egg @ https://github.com/mwrlabs/drozer/releases/download/2.4.2/drozer-2.4.2-py2.7.egg
