### ISSUE TITLE
run scanner.provider.injection has trouble processing

### ISSUE THREAD

**Issue by wlc520123** [mwrlabs/drozer#233]
### Steps to reproduce
1.install drozer 2.3.4 egg
2.open cmd 
3.input d:
4.adb forward tcp:31415 tcp:31415
5.d:\drozer\drozer.bat console connect
6.run scanner.provider.injection

### Expected behaviour
run this command corectly.

### Actual behaviour
has a wanning like this:
`Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Jieying.Li>D:\
'D:\' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Jieying.Li>d:

D:\>D:\drozer\drozer.bat console connect
Selecting 24f3fe6991d8edaf (SPRD SP9830A 5.1)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

drozer Console (v2.3.4)
dz> run scanner.provider.injection
Scanning addon.sprd.browser.bookmark...
D:\Java\jdk1.7.0_75\bin\javac.exe -cp D:\drozer\lib\drozer\lib\android.jar ZipUt
il.java
D:\drozer\lib\drozer\lib\dx.bat --dex --output 4a78a7a38b67b985beccf6efac92375b.
apk ZipUtil.class

trouble processing:
bad class file magic (cafebabe) or version (0033.0000)
...while parsing ZipUtil.class
...while processing ZipUtil.class
1 warning
no classfiles specified
drozer could not find or compile a required extension library.

dz>`

### Environment
windows 7
**Operating system**:

**Java Version:**
1.7.0_75
**Android Version:**
android phone: 5.1

**Drozer Version:** 
2.3.4
**Install Method:** Built from source/.deb/.exe/..

### Drozer Config
```
Contents of ~/.drozer_config
`[executables]
java = D:\Java\jdk1.7.0_75\bin\
javac= D:\Java\jdk1.7.0_75\bin\javac.exe`

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
`D:\>D:\drozer\drozer.bat console connect --debug
Selecting 24f3fe6991d8edaf (SPRD SP9830A 5.1)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

drozer Console (v2.3.4 debug mode)
dz> run scanner.provider.injection
Scanning addon.sprd.browser.bookmark...
D:\Java\jdk1.7.0_75\bin\javac.exe -cp D:\drozer\lib\drozer\lib\android.jar ZipUt
il.java
D:\drozer\lib\drozer\lib\dx.bat --dex --output 4a78a7a38b67b985beccf6efac92375b.
apk ZipUtil.class

trouble processing:
bad class file magic (cafebabe) or version (0033.0000)
...while parsing ZipUtil.class
...while processing ZipUtil.class
1 warning
no classfiles specified
exception in module: RuntimeError: drozer could not find or compile a required e
xtension library.

Traceback (most recent call last):
  File "D:\drozer\lib\drozer\console\session.py", line 394, in do_run
    module.run(argv[1:])
  File "D:\drozer\lib\drozer\modules\base.py", line 183, in run
    result = self.execute(arguments)
  File "D:\drozer\lib\drozer\modules\scanner\provider\injection.py", line 25, in
 execute
    for uri in self.findAllContentUris(arguments.package_or_uri):
  File "D:\drozer\lib\drozer\modules\common\provider.py", line 196, in findAllCo
ntentUris
    uris = uris.union(self.__search_package(package))
  File "D:\drozer\lib\drozer\modules\common\provider.py", line 316, in __search_
package
    for (path, content_uris) in self.findContentUris(package.packageName):
  File "D:\drozer\lib\drozer\modules\common\provider.py", line 228, in findConte
ntUris
    dex_file = self.extractFromZip("classes.dex", path, self.cacheDir())
  File "D:\drozer\lib\drozer\modules\common\zip_file.py", line 14, in extractFro
mZip
    ZipUtil = self.loadClass("common/ZipUtil.apk", "ZipUtil")
  File "D:\drozer\lib\drozer\modules\common\loader.py", line 30, in loadClass
    Module.cache_klass(".".join([source, klass]), loader.loadClass(klass))
  File "D:\drozer\lib\pydiesel\reflection\utils\class_loader.py", line 28, in lo
adClass
    return self.getClassLoader().loadClass(klass);
  File "D:\drozer\lib\pydiesel\reflection\utils\class_loader.py", line 51, in ge
tClassLoader
    raise RuntimeError("drozer could not find or compile a required extension li
brary.\n")
RuntimeError: drozer could not find or compile a required extension library.
dz>`

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```
`--------- beginning of main

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CSQ: 31,99

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CESQ: 60,99,255,255,255,255

D/SignalStrengthUtilsForOperator(  576): getOperatorLteLevel=0

D/KeyguardUpdateMonitor(  752): received broadcast android.intent.action.TIME_TICK

D/KeyguardUpdateMonitor(  752): handleTimeUpdate

--------- beginning of system

D/AlarmManager(  576): waitForAlarm result:8

D/AlarmManager(  576): triggerList.size = 1, hasWakeup = false

D/AlarmManager(  576): sending alarm.type = 3, action = android.intent.action.TIME_TICK, cn = null, operation = PendingIntent{25246942: PendingIntentRecord{139f1d53 android broadcastIntent}}

D/BroadcastQueue(  576): Add broadcastBroadcastRecord{e7e3c67 u-1 android.intent.action.TIME_TICK} into (foreground/order), now header = BroadcastRecord{e7e3c67 u-1 android.intent.action.TIME_TICK}, size = 1

D/PowerManagerService(  576): acquireWakeLockInternal: lock=941428363, flags=0x40000001, tag="*alarm*", ws=WorkSource{1000}, uid=1000, pid=576

D/AlarmManager(  576): setImpl() action = android.intent.action.TIME_TICK, component = null, type = 3, standalone=true, operation = PendingIntent{25246942: PendingIntentRecord{139f1d53 android broadcastIntent}} tElapsed=163561354, maxElapsed=163561354, interval=0, when = 1325539560000, triggerTime = 2012-01-03 05:26:00

D/PowerGuruService(  576): NEW_ALARM

D/PowerGuruService(  576): not a WAKEUP alarm, return!

D/gralloc.sc8830(  170): fb_post fps = 0.027930

D/BroadcastQueue(  576): Finished with ordered broadcast BroadcastRecord{e7e3c67 u-1 android.intent.action.TIME_TICK}, [foreground], remain = 0

D/PowerManagerService(  576): releaseWakeLockInternal: lock=941428363 [*alarm*], flags=0x0

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CSQ: 31,99

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CESQ: 63,99,255,255,255,255

D/SignalStrengthUtilsForOperator(  576): getOperatorLteLevel=0

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CSQ: 31,99

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CESQ: 62,99,255,255,255,255

D/SignalStrengthUtilsForOperator(  576): getOperatorLteLevel=0

D/ThermalCvtGovernor( 1026): Sum: 978909 cala times: 30

D/ThermalCvtGovernor( 1026): cpu sensor average temp: 32630

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CSQ: 31,99

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CESQ: 61,99,255,255,255,255

D/SignalStrengthUtilsForOperator(  576): getOperatorLteLevel=0

D/BatteryService(  576): Sending ACTION_BATTERY_CHANGED.  level:100, scale:100, status:5, health:2, present:true, voltage: 4215, temperature: 200, technology: Li-ion, AC powered:false, USB powered:true, Wireless powered:false, icon:17303150, invalid charger:0

D/KeyguardUpdateMonitor(  752): received broadcast android.intent.action.BATTERY_CHANGED

D/PowerGuruService(  576): CMD_BATTERY_CHANGED (newPlugType = 2)

D/KeyguardUpdateMonitor(  752): handleBatteryUpdate

D/WifiController(  576): battery changed pluggedType: 2

D/PhoneKeeperService( 1087): onReceive ACTION_BATTERY_CHANGED currentLevel = 100

D/ModeChange( 1087): isLowBatteryOn = false

D/WifiController(  576): handleMessage: E msg.what=155652

D/WifiController(  576): processMsg: ApStaDisabledState

D/WifiController(  576): processMsg: DefaultState

D/WifiController(  576): handleMessage: X

D/BatteryMeterView(  752): batteryStatus = 5

D/BatteryMeterView(  752): level should be =100

D/BatteryMeterView(  752):  non-charge: level =100

D/BatteryMeterView(  752): batteryStatus = 5

D/BatteryMeterView(  752): level should be =100

D/BatteryMeterView(  752):  non-charge: level =100

D/BatteryMeterView(  752): batteryStatus = 5

D/BatteryMeterView(  752): level should be =100

D/BatteryMeterView(  752):  non-charge: level =100

D/gralloc.sc8830(  170): fb_post fps = 0.041311

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CSQ: 31,99

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CESQ: 62,99,255,255,255,255

D/SignalStrengthUtilsForOperator(  576): getOperatorLteLevel=0

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CSQ: 31,99

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CESQ: 63,99,255,255,255,255

D/SignalStrengthUtilsForOperator(  576): getOperatorLteLevel=0

D/ThermalCvtGovernor( 1026): Sum: 1492738 cala times: 45

D/ThermalCvtGovernor( 1026): cpu sensor average temp: 33171

D/        (  185): XmlStorage::handleEvent()

D/        (  185): /data/sprdinfo/apr.xml file is created

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CSQ: 31,99

D/phoneserver(  205): Rev TID [233]: mux=/dev/stty_lte0: +CESQ: 63,99,255,255,255,255

D/SignalStrengthUtilsForOperator(  576): getOperatorLteLevel=0

`

**Comment by HenryHoggard** [comment]
Hi @wlc520123,

Thanks for the bug report. I believe this is because you are using Drozer 2.3.4 with Java 7, which isn't supported. Please can you try the either of the following configurations and let me know if it works.
* Drozer 2.3.4 with Java 6
* Drozer 2.4.1 (Alpha) with Java 7

**Comment by wlc520123** [comment]
I have had  JDK+JRE 7 in my computer ( windows), So I downloaded 2.4.1 egg file.
I installed it with " easy_install drozer-2.4.1-py2.7.egg " command. But there is no success. The result is:

`D:\>easy_install D:\drozer-2.4.1-py2.7.egg
Processing drozer-2.4.1-py2.7.egg
removing 'd:\python27\lib\site-packages\drozer-2.4.1-py2.7.egg' (and everything
under it)
creating d:\python27\lib\site-packages\drozer-2.4.1-py2.7.egg
Extracting drozer-2.4.1-py2.7.egg to d:\python27\lib\site-packages
Adding drozer 2.4.1 to easy-install.pth file
Installing drozer script to D:\Python27\Scripts
Installing drozer-complete script to D:\Python27\Scripts

Installed d:\python27\lib\site-packages\drozer-2.4.1-py2.7.egg
Processing dependencies for drozer==2.4.1
Searching for cryptography>=0.7
Reading https://pypi.python.org/simple/cryptography/
Downloading https://pypi.python.org/packages/99/df/71c7260003f5c469cec3db4c54711
5df39e9ce6c719a99e067ba0e78fd8a/cryptography-1.7.2.tar.gz#md5=fade66de437392ed1b
a6980768626204
Best match: cryptography 1.7.2
Processing cryptography-1.7.2.tar.gz
Writing c:\users\jieying.li\appdata\local\temp\easy_install-iejspm\cryptography-
1.7.2\setup.cfg
Running cryptography-1.7.2\setup.py -q bdist_egg --dist-dir c:\users\jieying.li\
appdata\local\temp\easy_install-iejspm\cryptography-1.7.2\egg-dist-tmp-oziyzy
_configtest.c
warning: no files found matching 'win64.obj' under directory 'c'
warning: no files found matching 'Makefile' under directory 'doc'
warning: no files found matching 'py.cleanup' under directory 'demo'
warning: no files found matching 'embedding_test.c' under directory 'demo'
warning: no files found matching 'manual.c' under directory 'demo'
_cffi_backend.c
ffi.c
prep_cif.c
types.c
win32.c
   Creating library build\temp.win32-2.7\Release\c\_cffi_backend.lib and object
build\temp.win32-2.7\Release\c\_cffi_backend.exp

Installed c:\users\jieying.li\appdata\local\temp\easy_install-iejspm\cryptograph
y-1.7.2\.eggs\cffi-1.9.1-py2.7-win32.egg
Searching for pycparser
Reading https://pypi.python.org/simple/pycparser/
Downloading https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809
a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz#md5=ca98dcb50bc1276f230118
f6af5a40c7
Best match: pycparser 2.17
Processing pycparser-2.17.tar.gz
Writing c:\users\jieying.li\appdata\local\temp\easy_install-iejspm\cryptography-
1.7.2\temp\easy_install-yd9904\pycparser-2.17\setup.cfg
Running pycparser-2.17\setup.py -q bdist_egg --dist-dir c:\users\jieying.li\appd
ata\local\temp\easy_install-iejspm\cryptography-1.7.2\temp\easy_install-yd9904\p
ycparser-2.17\egg-dist-tmp-8__iex
warning: no previously-included files matching 'yacctab.*' found under directory
 'tests'
warning: no previously-included files matching 'lextab.*' found under directory
'tests'
warning: no previously-included files matching 'yacctab.*' found under directory
 'examples'
warning: no previously-included files matching 'lextab.*' found under directory
'examples'
zip_safe flag not set; analyzing archive contents...
pycparser.ply.lex: module references __file__
pycparser.ply.lex: module MAY be using inspect.getsourcefile
pycparser.ply.yacc: module references __file__
pycparser.ply.yacc: module MAY be using inspect.getsourcefile
pycparser.ply.yacc: module MAY be using inspect.stack
pycparser.ply.ygen: module references __file__
creating c:\users\jieying.li\appdata\local\temp\easy_install-iejspm\cryptography
-1.7.2\.eggs\pycparser-2.17-py2.7.egg
Extracting pycparser-2.17-py2.7.egg to c:\users\jieying.li\appdata\local\temp\ea
sy_install-iejspm\cryptography-1.7.2\.eggs

Installed c:\users\jieying.li\appdata\local\temp\easy_install-iejspm\cryptograph
y-1.7.2\.eggs\pycparser-2.17-py2.7.egg
no previously-included directories found matching 'docs\_build'
warning: no previously-included files matching '*' found under directory 'vector
s'
_openssl.c
build\temp.win32-2.7\Release\_openssl.c(434) : fatal error C1083: Cannot open in
clude file: 'openssl/opensslv.h': No such file or directory
error: c:\users\jieying.li\appdata\local\temp\easy_install-iejspm\cryptography-1
.7.2\.eggs\cffi-1.9.1-py2.7-win32.egg\_cffi_backend.pyd:

D:\>`

Is it installed successfully? And Then how to run drozer server?

**Comment by wlc520123** [comment]
Then I tried like this, But it failed to run drozer...

D:\>python
Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> help('modules')

Please wait a moment while I gather a list of all available modules...

drozer Server requires Twisted to run.
Run 'easy_install twisted==10.2.0' to fetch this dependency.

D:\>easy_install twisted==10.2.0
Searching for twisted==10.2.0
Best match: twisted 10.2.0
Processing twisted-10.2.0-py2.7-win32.egg
twisted 10.2.0 is already the active version in easy-install.pth
Installing cftp.py script to D:\Python27\Scripts
Installing ckeygen.py script to D:\Python27\Scripts
Installing conch.py script to D:\Python27\Scripts
Installing lore.py script to D:\Python27\Scripts
Installing mailmail.py script to D:\Python27\Scripts
Installing manhole.py script to D:\Python27\Scripts
Installing mktap.py script to D:\Python27\Scripts
Installing pyhtmlizer.py script to D:\Python27\Scripts
Installing tap2deb.py script to D:\Python27\Scripts
Installing tap2rpm.py script to D:\Python27\Scripts
Installing tapconvert.py script to D:\Python27\Scripts
Installing tkconch.py script to D:\Python27\Scripts
Installing trial.py script to D:\Python27\Scripts
Installing twistd.py script to D:\Python27\Scripts

Using d:\python27\lib\site-packages\twisted-10.2.0-py2.7-win32.egg
Processing dependencies for twisted==10.2.0
Finished processing dependencies for twisted==10.2.0

D:\>easy_install twisted==10.2.0
Searching for twisted==10.2.0
Best match: twisted 10.2.0
Processing twisted-10.2.0-py2.7-win32.egg
twisted 10.2.0 is already the active version in easy-install.pth
Installing cftp.py script to D:\Python27\Scripts
Installing ckeygen.py script to D:\Python27\Scripts
Installing conch.py script to D:\Python27\Scripts
Installing lore.py script to D:\Python27\Scripts
Installing mailmail.py script to D:\Python27\Scripts
Installing manhole.py script to D:\Python27\Scripts
Installing mktap.py script to D:\Python27\Scripts
Installing pyhtmlizer.py script to D:\Python27\Scripts
Installing tap2deb.py script to D:\Python27\Scripts
Installing tap2rpm.py script to D:\Python27\Scripts
Installing tapconvert.py script to D:\Python27\Scripts
Installing tkconch.py script to D:\Python27\Scripts
Installing trial.py script to D:\Python27\Scripts
Installing twistd.py script to D:\Python27\Scripts

Using d:\python27\lib\site-packages\twisted-10.2.0-py2.7-win32.egg
Processing dependencies for twisted==10.2.0
Finished processing dependencies for twisted==10.2.0

D:\>python
Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> help('modules')

Please wait a moment while I gather a list of all available modules...

drozer Server requires Twisted to run.
Run 'easy_install twisted==10.2.0' to fetch this dependency.

D:\>python drozer
D:\Python27\python.exe: can't find '__main__' module in 'drozer'

D:\>python
Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> help('modules')

Please wait a moment while I gather a list of all available modules...

drozer Server requires Twisted to run.
Run 'easy_install twisted==10.2.0' to fetch this dependency.

D:\>

**Comment by amarekano** [comment]
Hi @wlc520123, It appears that your installation of twisted didn't succeed for some reason.
Unfortunately we can't help you with issues related to installation of dependencies. Google's your friend here ;)

Please reopen this issue if you have trouble installing/using drozer itself.
