### ISSUE TITLE
Android Wear Support

### ISSUE THREAD

**Issue by Mdalessi** [mwrlabs/drozer#234]
I see that Issue 184 dealt with this, but I am having trouble replicating: 
$ drozer agent build --rogue
$ adb install agent.apk
$ drozer server start
$ adb shell 'am startservice -n com.mwr.dz/.Agent'
$ drozer console connect 

When I only have access to the device via adb over bluetooth. I changed the adb commands to adb -s 127.0.0.1:4444 install agent.apk and  adb -s 127.0.0.1:4444 shell 'am startservice -n com.mwr.dz/.Agent. However, when I run "drozer console connect", I receive "No devices available."

**Comment by HenryHoggard** [comment]
@Mdalessi you need to do:

```
drozer console connect --server <ip>
```
or
```
 adb -s 127.0.0.1:4444 forward tcp:31415 tcp:31415
drozer console connect
```
