### ISSUE TITLE
drozer 2.4.1 error no 2 no such file or directory 

### ISSUE THREAD

**Issue by kaleemshaik7867** [mwrlabs/drozer#236]
### Steps to reproduce
Tried to install the drozer from source on mac os sierra . But not able to get into the drozer shell

### Actual behaviour
Not able to get the shell when I ran "drozer console connect --debug"

### Environment

**Operating system**:
MAC OS sierra 10.12.1
**Java Version:**
1.7.0
**Android Version:**
Geny motion kitkat 
**Drozer Version:** 
2.4.1
**Install Method:** Built from source/.deb/.exe/..
built
![screen shot 2017-01-13 at 5 48 42 pm](https://cloud.githubusercontent.com/assets/7692857/21929820/e3cf4e74-d9b8-11e6-8a26-5d04002494d3.png)
 from source
### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```
[Errno 2] No such file or directory
### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by kaleemshaik7867** [comment]
I have set it up the drozer/bin and drozer/src and drozer/test path in $PATH variable

**Comment by HenryHoggard** [comment]
Hi @kaleemshaik7867  what version of python are you using?

**Comment by kaleemshaik7867** [comment]
@HenryHoggard  I am using python 2.7.10

**Comment by kaleemshaik7867** [comment]
@HenryHoggard Please let me know if you need any more information. I have been working on this but unable to solve.

**Comment by HenryHoggard** [comment]
Can you paste the commands you used to build Drozer? I will try reproduce.

**Comment by kaleemshaik7867** [comment]
@HenryHoggard  I was able to solve this. Some dependencies are missing. Installed all those and working fine. Thanks for your support. Please close the issue.

**Comment by ah8r** [comment]
@kaleemshaik7867 I'm having a similar issue. What dependencies did you install to sort this out?

**Comment by pharazone** [comment]
same issue
