### ISSUE TITLE
ImportError: No module named drozer

### ISSUE THREAD

**Issue by Tangyiming** [mwrlabs/drozer#237]
when i try to install drozer in kali-linux,some thing goes wrong like this:

```
root@kali:~# git clone https://github.com/mwrlabs/drozer/
Cloning into 'drozer'...
remote: Counting objects: 8387, done.
remote: Total 8387 (delta 0), reused 0 (delta 0), pack-reused 8387
Receiving objects: 100% (8387/8387), 40.34 MiB | 79.00 KiB/s, done.
Resolving deltas: 100% (4101/4101), done.
Checking connectivity... done.
root@kali:~# cd drozer/
root@kali:~/drozer# python setup.py build
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from drozer import meta
ImportError: No module named drozer
root@kali:~/drozer# 

```

anyone knows how to solve this? thank you

**Comment by HenryHoggard** [comment]
Hi @Tangyiming,

**Duplicate Issues:** #174, #222, #148, #218 
**Further Reading:** https://github.com/mwrlabs/drozer/wiki/Running-on-the-edge

You need to set the environment variable`PYTHONPATH` to `/path/to/drozer/src`.

Let us know if you are still experiencing this issue after this.

**Comment by HenryHoggard** [comment]
FYI https://github.com/mwrlabs/drozer/pull/231 was merged today, so in future releases you won't have to set the pythonpath.

**Comment by Tangyiming** [comment]
@HenryHoggard thkx nice work
