### ISSUE TITLE
extra info needed in README

### ISSUE THREAD

**Issue by digininja** [mwrlabs/drozer#240]
In the README you say:

```
Drozer can be installed using Android Debug Bridge (adb).

$ adb install drozer.apk
```

But if you build from source you don't get drozer.apk, you get these two:

```
# find . -name '*apk'
./src/drozer/lib/rogue-agent.apk
./src/drozer/lib/standard-agent.apk
./build/lib.linux-x86_64-2.7/drozer/lib/rogue-agent.apk
./build/lib.linux-x86_64-2.7/drozer/lib/standard-agent.apk
```

The download from your site is drozer-agent-2.3.4.apk so that doesn't match either.

I think it would be better if you used a filename that exists or point at where to find them.

**Comment by HenryHoggard** [comment]
Hi @digininja,

Does PR https://github.com/mwrlabs/drozer/pull/242 solve your issue? (Line 60).

**Comment by digininja** [comment]
You've got the specific version in the link but x's in the adb command. I'd
change the link to go to the page with all the downloads rather than a
specific one so you don't need to remember to update the readme on each new
release.
