### ISSUE TITLE
Windows installer - md5 checksum mismatch

### ISSUE THREAD

**Issue by Grindle-git** [mwrlabs/drozer#251]
### Steps to reproduce
1. Download Drozer windows installer from here: https://github.com/mwrlabs/drozer/releases/download/2.3.4/drozer-installer-2.3.4.zip
2. Check MD5 checksum with Microsoft's File Checksum Integrity Verifier
`>fciv -md5 drozer-installer-2.3.4.zip`
output:
`//
// File Checksum Integrity Verifier version 2.05.
//
1598fd47d33abde0f5dc2360d2f740be drozer-installer-2.3.4.zip`
3. MD5 at https://labs.mwrinfosecurity.com/tools/drozer/ is '2052f6d7271bbd524f27867d8834c17b'

### Expected behaviour
The MD5 should match

### Actual behaviour
The MD5 does not match

**Comment by amarekano** [comment]
Hi @Grindle-git, thanks for reporting this to us. We'll have our website updated with the right hash.

**Comment by amarekano** [comment]
Hi @Grindle-git, this has been rectified. Thanks again for bringing this to our attention :)
