### ISSUE TITLE
Any plans for pip or wheel support

### ISSUE THREAD

**Issue by anantshri** [mwrlabs/drozer#252]
egg is now considered obsolete any plans on pushing this to pip repository or providing wheel package

https://packaging.python.org/wheel_egg/

**Comment by HenryHoggard** [comment]
Hi @anantshri thanks for the suggestion, we are looking into implementing this.

**Comment by anantshri** [comment]
That would be awesome. Right now i am creating a python-drozer package for https://repo.androidtamer.com via https://github.com/AndroidTamer/Packaging_Tools/blob/master/Build/drozer/build.sh

**Comment by amarekano** [comment]
Added with PR #287
