### ISSUE TITLE
any specific reason's for fixing dependencies version

### ISSUE THREAD

**Issue by anantshri** [mwrlabs/drozer#253]
https://github.com/mwrlabs/drozer/blob/develop/setup.py#L53
```
 install_requires = ["protobuf==2.6.1","pyopenssl==16.2", "pyyaml==3.11"],
```
Is there any hard requirement. what if there is a new pip out for example pyyaml has 3.12 version also released.

**Comment by HenryHoggard** [comment]
Specific PyOpenSSL versions were used to fix previous issues such as #239. I will check protobuf and pyyaml to see if we can lift the requirement.

**Comment by anantshri** [comment]
instead of fixing the version can we mark it like >= that will allow us to still use the newer versions and ensure we don't use version less then the version in use.

**Comment by amarekano** [comment]
Hi @anantshri, Thank you for bringing this to our attention. PR #259  should resolve this issue.
