### ISSUE TITLE
2.4.3 any ETA

### ISSUE THREAD

**Issue by anantshri** [mwrlabs/drozer#260]
any ETA for 2.4.3 version of it. I saw some tags were added a few days back but then they were removed.

**Comment by amarekano** [comment]
Hi @anantshri, we should have a new release in the next couple of weeks. We're currently working on improving our build process.

Is there a particular feature you're looking for in our next release?

**Comment by anantshri** [comment]
Cool. would be waiting for it.

I am looking forward for 3 things.
1) https://github.com/mwrlabs/drozer/pull/259 <- native deb building from source.
2) https://github.com/mwrlabs/drozer/issues/252 <- pip package
3) #203 support for x86 systems.

**Comment by amarekano** [comment]
Hi @anantshri, I've added support for deb packaging and x86 arch to develop and Henry's currently working on adding pip support.

A new version of drozer will be made available soon. For updates on the latest releases follow us on twitter @mwrdrozer.
