### ISSUE TITLE
Sieve apk not connecting to the service

### ISSUE THREAD

**Issue by silvianerea** [mwrlabs/drozer#266]
I am working with an android emulator in virtualbox and everything seems to work fine, i have internet as i am able to use the browser and also google play, but when i try to use sieve and add a new password i got the following error message:

> Unable to connect to the Service, force quit the app and try again

I have two network adapters:
   -In host-only to connect with Drozer. And i am able to perfectly work with Drozer
   -NAT - Paravirtualized network adapater (virtio-net)

I am working on my laptop, im not sure what's happening and if it has something to do with working on a laptop.

**Comment by amarekano** [comment]
Hi @silvianerea, in order to debug this I'd like some additional information:
1. How often do you get this error? Is it every time you save/add a password?
2. Could you provide me the inputs you used that caused this error? This would be the service, username, email and password combination.

**Comment by amarekano** [comment]
Closed due to lack of response. Please reopen this issue with the information requested if you're still unable to use Sieve.

**Comment by Bsunny** [comment]
Hi @amarekano 
I used this information:
Service- Serv1
usename - Serv1
email - Serv1@gmail.com
password -Serv@1
again - Serv@1

I clicked on save and got the same error 'nable to connect to the Service, force quit the app and try again'
Please help.

**Comment by Bsunny** [comment]
Also When i started the app and login , i get following error:
![image](https://user-images.githubusercontent.com/31987393/40174954-43da6706-59f4-11e8-8623-55824c323a73.png)

**Comment by juanduarte1927** [comment]
Bsunny, you can fix the problem? I don´t know how fix it
