### ISSUE TITLE
Kali Linux Unable to install drozer

### ISSUE THREAD

**Issue by sumeshgopu** [mwrlabs/drozer#267]
### Steps to reproduce
1.Install Kali Linux from https://www.kali.org/downloads/ version 2017.1
2.Install dependencies
i) apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev libssl-dev
ii) easy_install greenlet
iii) easy_install gevent

### Actual behaviour
Installation Failed

### Environment

**Operating system*Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux*:

**Java Version:openjdk version "1.8.0_121"
**Drozer Version:*2.3.4* 

**Install Method:** Built from source

```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
root@kali:~/Desktop/drozer-2.3.4# easy_install drozer-2.3.4-py2.7.egg 
Processing drozer-2.3.4-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/drozer-2.3.4-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/drozer-2.3.4-py2.7.egg
Extracting drozer-2.3.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
drozer 2.3.4 is already the active version in easy-install.pth
Installing drozer script to /usr/local/bin
Installing drozer-complete script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/drozer-2.3.4-py2.7.egg
Processing dependencies for drozer==2.3.4
Searching for pyopenssl==0.13
Reading https://pypi.python.org/simple/pyopenssl/
Downloading https://pypi.python.org/packages/8b/20/8f4230b281a2a9d0ee9e24fd89aeded0b25d40c84b3d61100a96438e1626/pyOpenSSL-0.13.tar.gz#md5=767bca18a71178ca353dff9e10941929
Best match: pyOpenSSL 0.13
Processing pyOpenSSL-0.13.tar.gz
Writing /tmp/easy_install-jV9Abs/pyOpenSSL-0.13/setup.cfg
Running pyOpenSSL-0.13/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jV9Abs/pyOpenSSL-0.13/egg-dist-tmp-3bAtnL
warning: no previously-included files matching '*.pyc' found anywhere in distribution
OpenSSL/crypto/crypto.c: In function ‘crypto_sign’:
OpenSSL/crypto/crypto.c:626:16: error: storage size of ‘md_ctx’ isn’t known
     EVP_MD_CTX md_ctx;
                ^~~~~~
OpenSSL/crypto/crypto.c:626:16: warning: unused variable ‘md_ctx’ [-Wunused-variable]
OpenSSL/crypto/crypto.c: In function ‘crypto_verify’:
OpenSSL/crypto/crypto.c:673:16: error: storage size of ‘md_ctx’ isn’t known
     EVP_MD_CTX md_ctx;
                ^~~~~~
OpenSSL/crypto/crypto.c:673:16: warning: unused variable ‘md_ctx’ [-Wunused-variable]
At top level:
OpenSSL/crypto/crypto.c:743:13: warning: ‘locking_function’ defined but not used [-Wunused-function]
 static void locking_function(int mode, int n, const char * file, int line) {
             ^~~~~~~~~~~~~~~~
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by amarekano** [comment]
Hi @sumeshgopu, could you try our latest version of Drozer.
https://github.com/mwrlabs/drozer/releases/tag/2.4.2

We've made a few improvements regarding Drozer's dependency on pyOpenSSL. Hopefully this alleviates the problem you're having.

**Comment by HenryHoggard** [comment]
@sumeshgopu please switch from Java 1.8 to Java 1.7. Drozer does not support Java 1.8.
