### ISSUE TITLE
[Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by Chaitanya209** [mwrlabs/drozer#269]
### Steps to reproduce
1. Getting operation not permitted error is displayed when tried to use "drozer console connect --debug"

Krishnas-MacBook-Pro:~ krishnachaitanya$ drozer console connect --debug
Selecting 16829fa740b1831f (LGE Nexus 4 5.1.1)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

drozer Console (v2.3.4 debug mode)
[Errno 1] Operation not permitted

**Comment by amarekano** [comment]
Hi @Chaitanya209, could you try our latest drozer release and let us know if you still unable to get it working.
The latest release can be found at https://github.com/mwrlabs/drozer/releases/tag/2.4.2

**Comment by amarekano** [comment]
Closed due to lack of response. Please reopen if you're still unable to get drozer working.

**Comment by rootbakar** [comment]
Hi Team,,

macos@rootbakar scripts-2.7 % python2.7 drozer console connect
/Users/xxx/Library/Python/2.7/lib/python/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
Selecting 86a5cfb714c63aba (unknown SSL 7.0)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

drozer Console (v2.4.4)
[Errno 1] Operation not permitted

**Comment by rootbakar** [comment]
After warning UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

**Comment by rootbakar** [comment]
i install python2.7 -m pip install service_identity

**Comment by aasyria** [comment]
this issue still there.
same Error .
Mac OS Big Sur

**Comment by askDing** [comment]
this issue still there

**Comment by pstoeckle** [comment]
@askDing  The changes in https://github.com/FSecureLABS/drozer/pull/392 solved the problem for me.
