### ISSUE TITLE
Unknown syntax tools.setup.busybox

### ISSUE THREAD

**Issue by pr0letariat** [mwrlabs/drozer#297]
### Steps to reproduce
1. `adb forward tcp:31415 tcp:31415`
2. `drozer console --server 127.0.0.1:31415 connect`
3. `dz> tools.setup.busybox
*** Unknown syntax: tools.setup.busybox`

### Expected behaviour
Installs busybox tools

### Actual behaviour
Unknown syntax error above

### Environment

**Operating system**:
`Distributor ID:	Ubuntu
Description: Ubuntu 16.04.3 LTS
Release: 16.04
Codename: xenial`

**Java Version:**
<code>
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
</code>

**Android Version:** 5.1.1

**Drozer Version:** `drozer Console (v2.3.4)`

**Install Method:** Install from .deb

Can anyone help?

**Comment by amarekano** [comment]
hey @pr0letariat, the right syntax is "run tools.setup.busybox"

Also, I recommend you use drozer 2.4.3 which includes busybox compiled for PIE and also adds support for busybox on x86 based devices. 
The latest drozer release can be found at: https://github.com/mwrlabs/drozer/releases/tag/2.4.3
