### ISSUE TITLE
Agent Build - [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by tamtam22** [mwrlabs/drozer#300]
### Steps to reproduce
1.  Run cmd
2. Run command `C:\Users\tamtam22>drozer agent build --permission com.twitter.android.permission.READ_DATA`

### Expected behaviour
agent.apk should be produced with the specified permission

### Actual behaviour
`[Errno 2] No such file or directory`

### Environment

**Operating system**:
Microsoft Windows [Version 10.0.15063]

**Java Version:** 
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Android Version:**
5.1

**Drozer Version:** 
2.3.4

**Install Method:**
Windows installer. Installed at C:\drozer

### Drozer Config
```
[remotes]
https|//raw.github.com/mwrlabs/drozer-modules/repository/ = https://raw.github.com/mwrlabs/drozer-modules/repository/

[executables]
java = C:\Program Files\Java\jdk1.8.0_144\bin
javac = C:\Program Files\Java\jdk1.8.0_144\bin\javac.exe
```

### Drozer Error Logs
n.a.

### ADB Logs
n.a.

**Comment by tamtam22** [comment]
I was just trying the example at https://books.google.com.sg/books?id=UgVhBgAAQBAJ&pg=PA252&lpg=PA252&dq=android+protect+against+a+protection+level+downgrade+attack&source=bl&ots=SXu3sgf9K0&sig=x8lEPMuQgPp0VlBDm92TXm-U9xo&hl=en&sa=X&ved=0ahUKEwjnyZ7M3JLWAhXqKsAKHaRpAfgQ6AEILDAB#v=onepage&q=android%20protect%20against%20a%20protection%20level%20downgrade%20attack&f=false

regarding protection level downgrade attack

**Comment by amarekano** [comment]
Hi @tamtam22, we've had a few issues with the drozer 2.3.4 on windows. These have been patched in the tip version of the develop branch. Could you please clone this branch and build drozer from source. Instructions to build are @ https://github.com/mwrlabs/drozer#building-for-windows

Also, I've noticed that you're using jdk1.8. Drozer currently only supports jdk1.7 and lower.

**Comment by tamtam22** [comment]
Just FYI for those reading this:

If you are building drozer in Windows using a fresh Python 2.7 and face "No module named setuptools", you should try download [get-pip.py](https://bootstrap.pypa.io/get-pip.py), run it `python get-pip.py` Then install upgrade pip which will also install the latest versions of `setuptools` and `wheel` with this `python -m pip install -U pip setuptools`

[Source](https://stackoverflow.com/a/43312980)
