### ISSUE TITLE
Getting "[Errno 2] No such file or directory" error when trying to connect to console.

### ISSUE THREAD

**Issue by ah8r** [mwrlabs/drozer#303]
### Steps to reproduce
1. Build latest drozer on OS X.
2. Install latest Drozer Agent on Android emulator.
3. Run Drozer Agent and forward ports.
4. Try to connect to console using drozer.

### Expected behaviour

I expect to be connected to the console.

### Actual behaviour

After running the `drozer connect console --debug` command I get the following:

```
Selecting fa28bb20bf5cd465 (unknown Android SDK built for x86_64 7.1)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

drozer Console (v2.4.3 debug mode)
[Errno 2] No such file or directory
```

### Environment

**Operating system**: OS X Sierra (10.12.6)

**Java Version:** 1.8.0_101

**Android Version:** 7.1

**Drozer Version:** 2.4.3

**Install Method:** Have tried building from source and also installing the drozer-2.4.3-py2-none-any.whl file from the releases page. Agent was installed from pre-built download.

### Drozer Config
```
[remotes]
https|//raw.github.com/mwrlabs/drozer-modules/repository/ = https://raw.github.com/mwrlabs/drozer-modules/repository/
```

### Drozer Error Logs
```
Selecting fa28bb20bf5cd465 (unknown Android SDK built for x86_64 7.1)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

drozer Console (v2.4.3 debug mode)
[Errno 2] No such file or directory
```

**Comment by soupwaylee** [comment]
You need JDK 1.7. Drozer does not support JDK 1.8 yet.

**Comment by amarekano** [comment]
Hey @ah8r, this may be an issue with the file permissions set on .drozer_config. Could you attempt deleting this file and reinstalling drozer.

If you're attempting to build drozer from source you would require java 1.7. Drozer currently doesn't support java 1.8.

The latest drozer releases can be found at https://github.com/mwrlabs/drozer/releases

**Comment by jdonsec** [comment]
Environment
**Operating system:** OS Catalina

**Java Version:** 1.7.0_80

**Android Version:** 10

**Install Method:** https://github.com/fujiokayu/Installing-Drozer-on-macOS-Catalina

**Drozer Version:** 2.4.4

I keep getting the error 2 as well.

[Errno 2] No such file or directory

**Comment by yannaingtun** [comment]
I also got this errno 2.
I solved the issue like following

 **$ rm ~/.drozer_history
 $ drozer console connect**
