### ISSUE TITLE
was there a 2.4.5 tag created and removed

### ISSUE THREAD

**Issue by anantshri** [mwrlabs/drozer#312]
Hi folks i am a bit confused and needed some clarity. I track drozer released by tapping into the rss feed provided by github releases. https://github.com/mwrlabs/drozer/releases.atom

a new entry was created on "November 09, 2017 at 03:27AM" details : https://github.com/AndroidTamer/Tools_Repository/issues/312 

which suggested a new tag 2.4.5 however it doesn't appears here. Just wanted to be sure i am not missing anything. 

1. Can you please confirm if 2.4.4 is the latest release 
2. Can you please if you can suggest what happened to 2.4.5

**Comment by HenryHoggard** [comment]
2.4.4 is the latest release.
