### ISSUE TITLE
Installing Drozer via Python Wheel error

### ISSUE THREAD

**Issue by chocologurt** [mwrlabs/drozer#317]
Hi, 

I am currently trying to install Drozer in an Ubuntu environment and tried using Python Wheel to install Drozer. When I tried to run the command 

 `sudo pip install drozer-2.4.3-py2-none-any.whl`
 
It stated this 

> Processing ./drozer-2.4.3-py2-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 577, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 798, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 705, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 617, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 500, in unzip_file
    zipfp = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/home/wq/Desktop/Drozer/drozer/drozer-2.4.3-py2-none-any.whl'

I tried changing the Drozer version from 2.4.3 to 2.4.4 and still received the same error. Can anyone help me please?

**Comment by ParticularName** [comment]
@chocologurt I am facing the same issue.Can you tell me how did you resolve it?

**Comment by sidh104** [comment]
how was this resolved

**Comment by savagejen** [comment]
Here try this: 
Sudo -H pip install service_identity --upgrade --ignore-installed pyasn1 six
Sudo -H pip install --ignore-installed matplotlib 
sudo -H pip install tornado
sudo pip install drozer-2.4.4-py2-none-any.whl --upgrade --ignore-installed six

**Comment by skahure003** [comment]
that was helpful

**Comment by abhiunix** [comment]
> Here try this:
> Sudo -H pip install service_identity --upgrade --ignore-installed pyasn1 six
> Sudo -H pip install --ignore-installed matplotlib
> sudo -H pip install tornado
> sudo -H pip install drozer-2.4.4-py2-none-any.whl --upgrade --ignore-installed six
> sudo -H pip install twisted --ignore-installed six

Hey this was helpful for the installation only. when we try `drozer console connect` after port forwarding then it again start throwing the error!

**Comment by savagejen** [comment]
> > Here try this:
> > Sudo -H pip install service_identity --upgrade --ignore-installed pyasn1 six
> > Sudo -H pip install --ignore-installed matplotlib
> > sudo -H pip install tornado
> > sudo -H pip install drozer-2.4.4-py2-none-any.whl --upgrade --ignore-installed six
> > sudo -H pip install twisted --ignore-installed six
> 
> Hey this was helpful for the installation only. when we try `drozer console connect` after port forwarding then it again start throwing the `error!`
> `Traceback (most recent call last): File "/usr/bin/drozer", line 30, in <module> __import__("drozer.cli.%s" % (sys.argv[1])) File "/usr/lib/python2.7/dist-packages/drozer/cli/console.py", line 8, in <module> from drozer.console import Console File "/usr/lib/python2.7/dist-packages/drozer/console/__init__.py", line 4, in <module> from drozer.console.console import Console File "/usr/lib/python2.7/dist-packages/drozer/console/console.py", line 5, in <module> from pydiesel.api.protobuf_pb2 import Message File "/usr/lib/python2.7/dist-packages/pydiesel/api/__init__.py", line 9, in <module> from pydiesel.api.frame import Frame File "/usr/lib/python2.7/dist-packages/pydiesel/api/frame.py", line 3, in <module> from pydiesel.api.protobuf_pb2 import Message File "/usr/lib/python2.7/dist-packages/pydiesel/api/protobuf_pb2.py", line 4, in <module> from google.protobuf import descriptor as _descriptor ImportError: No module named google.protobuf`

I obviously am not in front of your machine, so I'm not sure why that's happening to you. Are you on osx, kali, something else? When you do 'pip list' does it not show protobuf? It's also weird that it's trying to use google.protobuf. You could always install google and then protobuf via pip and see if that resolves it. Seems odd though since protobuf doesn't show on my machine when I do pip list and I am able to use drozer just fine. 

It was announced that the drozer project is no longer being supported, so it looks like it's abandon-ware that will never be updated to python3. They released a docker image you can try.
