### ISSUE TITLE
drozer could not find or compile a required extension library.

### ISSUE THREAD

**Issue by baptistapedro** [mwrlabs/drozer#318]
By my research found out I'd need to do
'make apks' on /src/drozer/modules  but 

$ make apks
make: *** No rule to make target `apks'.  Stop.
$ make
make: *** No targets specified and no makefile found.  Stop.

Using latest version
https://github.com/mwrlabs/drozer/releases/download/2.4.4/drozer-2.4.4.tar.gz

That drozer error was thrown while trying to use app.package.native

**Comment by HenryHoggard** [comment]
If you want to run make apks do it using the source from git https://github.com/mwrlabs/drozer
