### ISSUE TITLE
    I want to use drozer to research android's holes, but i can not find the source code of sieve . Can you help me ? Where I can find them?

### ISSUE THREAD

**Issue by lcxing** [mwrlabs/drozer#319]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Environment

**Operating system**:

**Java Version:**

**Android Version:**

**Drozer Version:** 

**Install Method:** Built from source/.deb/.exe/..

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by HenryHoggard** [comment]
The source isn't released. However you can decompile the APK which can be found here: https://github.com/mwrlabs/drozer/releases/download/2.3.4/sieve.apk
