### ISSUE TITLE
unable to install drozer

### ISSUE THREAD

**Issue by awara552** [mwrlabs/drozer#328]
### Steps to reproduce
1. git clone https://github.com/mwrlabs/drozer/
2. cd drozer
3. python.exe setup.py bdist_msi
### Expected behaviour
should create Msi file

### Actual behaviour
'cut' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "setup.py", line 130, in <module>
    version = get_version(),
  File "setup.py", line 126, in get_version
    return subprocess.check_output(version_cmd,shell=True)
  File "C:\Python27\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '|', 'cut', '-c', '1-5']' returned non-zero exit status 255

### Environment

**Operating system**:windows 8.1

**Java Version:**1.8

**Android Version:**android studio 3.1.3

**Drozer Version:** latest clone

**Install Method:** Built from exe/..

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by aasdasdfasfasf** [comment]
I'm having a same issue. In setup.py i changed 121 line with  `version_cmd = ['git', 'describe', '--tags']`
but when i try to do drozer.bat console connect I get error: `Traceback (most recent call last):
  File "C:\Users\algirdas.bogusa\Desktop\drozer\bin\drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
ImportError: No module named drozer.cli.console`

**Comment by adityanarkar** [comment]
I am getting following error, after changing line 121 to return "2.4.3"
>  File "D:\Everything-else\drozer\VE\lib\site-packages\drozer\cli\console.py", line 6, in <module>
    from mwr.common import logger
ImportError: No module named mwr.common

**Comment by pj-alvarado10** [comment]
Try to install GnuWin32

**Comment by x11x** [comment]
I have submitted a PR #345
