### ISSUE TITLE
drozer build agent # On recent Kali

### ISSUE THREAD

**Issue by HanseSecure** [mwrlabs/drozer#338]
### Steps to reproduce
running 
`drozer agent build`
### Expected behaviour
Agent should be build.

### Actual behaviour
see Error Log below

### Environment

**Operating system**:
Recent Kali Rolling (2018.4)
**Java Version:**
openjdk 11.0.1 2018-10-16
**Android Version:**
several
**Drozer Version:** 
Agent Version: 2.3.3
drozer Version: 2.4.4
**Install Method:** Built from source/.deb/.exe/..
deb File from https://labs.mwrinfosecurity.com/tools/drozer/
### Drozer Config
```
default
```

### Drozer Error Logs
```
$drozer agent build

I: Using Apktool 2.2.4 on standard-agent.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/hansemann/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Version Mismatch: Consider updating your build(s)
Agent Version: 2.3.3
drozer Version: 2.4.4
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at com.android.signapk.SignApk.addDigestsToManifest(SignApk.java:169)
	at com.android.signapk.SignApk.main(SignApk.java:325)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more
could not sign the agent package
```

Thanks in advance 
Flo

**Comment by Nagaev** [comment]
Hi,

sun/misc/BASE64Encoder is no longer available in recent JDK versions.
You have to downgrade your version. I have just tried with 1.8.
Download it and change the default Java version with update-alternatives --config java

# drozer agent build
I: Using Apktool 2.2.4 on standard-agent.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Version Mismatch: Consider updating your build(s)
Agent Version: 2.3.3
drozer Version: 2.4.4
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
Done: /tmp/tmpdpKQGc/agent.apk

Cheers

Thomas

**Comment by HanseSecure** [comment]
Thanks, issue solved!
